### ISSUE TITLE
gapless play

### ISSUE THREAD

**Issue by lightonflux** [PaulWoitaschek/MaterialAudiobookPlayer#109]
Hello, i have several audiobook that have very hard cuts. Like **exactly** after the end of a sentence. And because MAP plays with a gap between them it is a bit annoying and uncomfortable to listen to. 

So one of the most beneficial features MAP could have is in my opinion gapless play, because it does help to immerse into an audiobook.

**Comment by Ph1b** [comment]
So you basically say, that it take too long to play a file after the last one ended?

**Comment by lightonflux** [comment]
Yes.

**Comment by Ph1b** [comment]
I have an idea what to do on this. Well keep you updated.

**Comment by ArchUser** [comment]
I have had this issue too especially with one where it was split into like 250 parts.

**Comment by Ph1b** [comment]
I made some trys with exoplayer, but wasnt able to properly implement speed control there. Once exoplayer hits that, we will have less gaps.

**Comment by PaulWoitaschek** [comment]
Implemented as of b2e22c0ec876d1648f7dfbba718f6bb90d22beda
