### ISSUE TITLE
Add an option to directly pick covers from the file system

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/MaterialAudiobookPlayer#301]
Rename 'edit cover' to 'Cover from internet'
Add a new option to select a cover from file system.
This shows a file picker which lets you select image files from disc. After a selection was made, open the drop dialog and set the cover.

**Comment by PaulWoitaschek** [comment]
Many thanks to @alilotfi !

If you want to implement other features let me know 👍

**Comment by alilotfi** [comment]
Thank you very much.
I love Kotlin and your project is an awesome playground with interesting challenges, so I like to participate in implementing other features too.
I will be happy if there is anything you would remind me.
