### ISSUE TITLE
Book progress in addition to chapter progress

### ISSUE THREAD

**Issue by Audio777** [PaulWoitaschek/MaterialAudiobookPlayer#338]
Hello,
It would be nice to have a feature that reveals more time info/details about the book currently played.
I would like to be able to cycle through the time already listened in this chapter / in this book and the time left for this chapter / this book. A bar showing the percentage would also be a nice way to implement this 4-way-info.

Great app so far!
Regards

**Comment by PaulWoitaschek** [comment]
Switch to the main view and choose list instead of grid. Then you will have a book progress view.
