### ISSUE TITLE
Suggestion: Complex books (study courses) with 1-2 level hierarhical folder structure management

### ISSUE THREAD

**Issue by zealotsinstc** [PaulWoitaschek/MaterialAudiobookPlayer#341]
Hello Material Player team!

I faced some issues while listening to complex study courses, that contains intependent sub-books on 1st and 2nd sub-folder levels.
I do understand that in order to listen them within current folder architecture I should simply bring all these books to the root level. The problem is that in my case I would get 40+ new books just for this single study course. And also this split folder structure would be difficult to maintain.

To keep everithing simple I think the best solution for such cases would be 3 simple steps:

<b>1</b>. Show subfolder name in the list of current book playback (see attached picture)
<b>2</b>. Provide a grouping option in the playback list based on the sub-folder structure (see attached picture)
(new controls may not be clickable for the playback - they gives user easy navigation in the huge playback list)
![screenshot_2015-10-23-09-12-29](https://cloud.githubusercontent.com/assets/15259189/10686608/7766704c-796e-11e5-954f-8d797ae446af.png)

<b>3</b>. Remember position in each file on the book that was not fully played (posted separately here https://github.com/Ph1b/MaterialAudiobookPlayer/issues/340)

Also, as you know sometimes books has chapters name in the subfolders. Steps above would provide better user experience for this case as well. 
May be you can consider even adding subfolder title to the home playback screen (with book image and buttons).

Thank you for your attention!

**Comment by PaulWoitaschek** [comment]
This has been discussed many times and to enable simplicity the structure won't get more complicated right now.
