### ISSUE TITLE
Bug: wrong file name in playback list

### ISSUE THREAD

**Issue by zealotsinstc** [PaulWoitaschek/MaterialAudiobookPlayer#342]
Hello!
Posting one small bug:

I have a book with these file names:
2_1_01.mp3
2_1_02.mp3
2_1_03.mp3
...

In the playback it's being displayed:

1- 2_1_01
<b>2 - _1_02</b>
3 - 2_1_03
...

![screenshot_2015-10-23-09-34-00](https://cloud.githubusercontent.com/assets/15259189/10686094/6f5259ac-7969-11e5-8722-1ea5b9ec3738.png)

Thanks!

**Comment by PaulWoitaschek** [comment]
This is a rare sideffect and will in most cases reduce complexity in naming.
