### ISSUE TITLE
Can't Access External SD card in Marshmallow

### ISSUE THREAD

**Issue by onespaceman** [PaulWoitaschek/MaterialAudiobookPlayer#349]
Upgraded to a build of Android M, but cannot select the external sd card as an audiobook folder.

The sd card is setup as portable storage which acts as it has for past Android versions (not as internal storage as introduced in Android M)

Other music players are able to see the audio files as normal.

In /storage the sd card is now assigned a name in the format XXXX-XXXX with each X being a hexadecimal character.

Hope all this helps. Thank you.

**Comment by Ph1b** [comment]
Is there another way to reach the storage?
Like /storage/emulated...?

MAP is no normal music player so you can't compare that. We let the user chose the directory itself, so its more important what i.e how file browsers do it.

**Comment by onespaceman** [comment]
There are folders in /mnt/media_rw, /mnt/runtime/default, /mnt/runtime/read, /mnt/runtime/write, all with the same XXXX-XXXX name. Those are the only other ways I could find to reach the sd card.

**Comment by soboapps** [comment]
What Device are you on? Are you using a Custom ROM?

**Comment by onespaceman** [comment]
LG G3 . It's an [alpha build of Cyanogenmod](http://www.invisiblek.org/roms/cm-13.0/vs985/) by the official device maintainer.

I mentioned above that I formatted it as portable storage which the article says is treated the same as in previous versions of android. (other than the mount name apparently).

**Comment by soboapps** [comment]
Have you posed the question to CyanogenMod?  Since it's an Alpha build, I would say it still may have a lot of bugs to work out.

**Comment by Ph1b** [comment]
[This](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/v2.4.2/audiobook/src/main/java/de/ph1b/audiobook/activity/FolderChooserActivity.java#L71) is the way we retrieve the list of storages at the moment. Maybe there is a reason it skipps the listed drives from CM.

**Comment by onespaceman** [comment]
For some reason I don't have a SECONDARY_STORAGE variable under printenv which is why it wasn't showing up.

By adding
>rv.add("/storage");  
or 
>rv.add"(/storage/XXXX-XXXX");
I was able to navigate to the storage, so no problems with permissions or anything else.

I'll just continue using internal storage, until I get some info if it's a problem with Android M or Cyanogenmod.

**Comment by GeorgeHahn** [comment]
I'm also having this issue (same configuration: CM13 nightly, LG G3, SD formatted as portable storage).

What would a proper fix look like? I'm going to make a quick build for myself with `rv.add("/storage");` , but I'd be happy to spend a little time trying to find a permanent solution.

**Comment by vityas-off** [comment]
Having this issue on moto x pure official 6.0.

**Comment by PaulWoitaschek** [comment]
Can you check if this works for you in 2.5.0.5? (you find it on the github release page or on google play beta).

I added `/storage` as a workaround *if* it has folders that have content.

**Comment by vityas-off** [comment]
Thanks, its works now!

**Comment by GeorgeHahn** [comment]
Version 2.5.0.5 from github works for me!

**Comment by PaulWoitaschek** [comment]
I still don't get the new change on marshmallow and what the correct way is to retrieve these paths.
It looks like it is the UUID of the sdcard. Can someone check that?

Please report if you find something unexpected. If the path changes after a reboot or sth like that the books won't be recognized any longer.

**Comment by vityas-off** [comment]
Not sure if this is related issue, but now i have some crashes on 2.5.0.5 which can be fixed only wiping app data. 
![screenshot_20160101-171332](https://cloud.githubusercontent.com/assets/15840124/12071263/9d260364-b0ab-11e5-87b8-edabd42792c5.png)

**Comment by aperomsik** [comment]
Just to confirm, 2.5.0.7.1 works for me on Moto G 2015 stock MM, (got the OTA today), using the "all" workaround.
