### ISSUE TITLE
Edit cover function does not search.

### ISSUE THREAD

**Issue by arzenthal** [PaulWoitaschek/MaterialAudiobookPlayer#353]
The searching of cover is not working as it used to. It cannot find any cover. I hav test it in different devices and happens the same.
Thanks for your help and the good work with the app.

Iván

**Comment by Ph1b** [comment]
Which version are you using?

**Comment by arzenthal** [comment]
2.4.2

**Comment by Ph1b** [comment]
This is because Google shut their image search API down.

We need a new solution for this. Any ideas someone?

**Comment by arzenthal** [comment]
Maybe an easy solution is to get the cover for a link, so first youi find an image in chrome and the copy and paste the link of the image in the app.

**Comment by skynetua** [comment]
Check there http://stackoverflow.com/questions/34035422/google-image-search-says-api-no-longer-available

**Comment by Ph1b** [comment]
I didn't discover a suitable solution for us there.

**Comment by ozbozz** [comment]
Can you not use Bing search? Granted, it's nowhere near as good as Google but it does seem to work. It's what Listen Audiobook Player uses and it works.

Is there a way you can get Material Player to detect a jpg/png that's inside the folder with the Audiobook file(s) and use that as the default cover if present? Perhaps if it has a specific name like "cover.jpg" or something?

**Comment by ozbozz** [comment]
Or even an option to choose a picture manually from the devices gallery?

**Comment by Ph1b** [comment]
Choosing pictures manually is on the list. Bing charges.

**Comment by arzenthal** [comment]
Its a pity that the new version has lost the cover searching function. I hope it will return soon because there are other similar apps that has it.

**Comment by Ph1b** [comment]
I guess they are not for free then. And as this is for free I can't purchase api access to sth like Bing myself.
At the moment there are about 30k users. If each one of them is just looking for a cover 3 times a month there would be about 100k queries. Bing would charge us 153,06 € ^^

**Comment by arzenthal** [comment]
You are right. So the solution will be to get the jpg files from the device. Anyway, thanks for your work.

**Comment by DebrodeD** [comment]
It looks like "Listen Audiobook Player" found a workaround that works, anyone know how they do this?

**Comment by PaulWoitaschek** [comment]
@DebrodeD 
> Can you not use Bing search? Granted, it's nowhere near as good as Google but it does seem to work. It's what Listen Audiobook Player uses and it works.

**Comment by DebrodeD** [comment]
Whoops, not sure how I missed that sorry. Checkout "smart audio book player", they have an interesting way of doing it too.

**Comment by DePingus** [comment]
How about a simple cover.jpg in each folder? Or even just use the first jpg it finds in each book's folder?

Alternatively, if people use 1 folder with tons of book audio files in them, you can do TheMoonIsAHarshMistree.mp3 and use a corresponding TheMoonIsAHarshMistree.jpg for it's cover.

It would be up to the user to find a cover picture, name it, and place it in the correct location though.

**Comment by skynetua** [comment]
We can do it in the way as Moon Reader do. Basically it opens google\yahoo!\bing image search page in webview and gets url directly from it. It's not so cute as was before but it works at least.

**Comment by PaulWoitaschek** [comment]
Already have that in mind and will implement this once home in 2 weeks.

**Comment by PaulWoitaschek** [comment]
Implemented as of [2.6.0](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v2.6.0)
