### ISSUE TITLE
Option to change sort order to "album name " for radio plays

### ISSUE THREAD

**Issue by t-richter** [PaulWoitaschek/MaterialAudiobookPlayer#356]
Hi,

I have a large collection of radio plays, that often contain of multiple parts.
I use iTunes for keeping the folders up-to-date on the PC side, so I have them structured in folders like this:
(example)
- My Radio Play (1) (<- iTunes album name)
    - 1-TrackName1
    - 2-TrackName2
- My Radio Play (2)
    - etc...

(ITunes automatically prepends the track number to the track title)

What happens now, when I put such a folder in Material Player, is: The books seemingly get ordered by the track name of the first track, so I have all 1st parts of the series on top, then all 2nd parts and so on.

I'd like it a lot more, if it was sorted by album name, if this tag is present, so all parts of the series would be right in line.

An option to select the order would also be very nice.

Thanks for the fantastic job so far!

p.s. using v2.4.2 from Play Store

p.p.s. If you point me in the right direction, I could also try to participate on getting this feature done, if you think it makes any sense.

**Comment by Ph1b** [comment]
I don't get it. What is the folder / file structure you have as input?

**Comment by t-richter** [comment]
WOW, that was fast reply!
<img width="421" alt="bildschirmfoto 2015-12-08 um 22 02 07" src="https://cloud.githubusercontent.com/assets/11031194/11668437/80073f80-9df7-11e5-943a-aee9bf30cc5e.png">

Attached a small screenshot, so maybe it becomes clearer.

**Comment by Ph1b** [comment]
So you have your Conni 1..11 and Hui Buh 6...7 all in one folder? How did you add it to MAP? As single books or as collection books? (This single folder icon or the multiple folder icon)

**Comment by t-richter** [comment]
Yes, I put them all in a single folder and added that as a collection of books.

**Comment by t-richter** [comment]
I now put the episodes of a play into different folders and added them separately (as collection of books)
I can liv with that, so you can now close this issue.
