### ISSUE TITLE
Time mark bug - Skipping to beggining of audio file

### ISSUE THREAD

**Issue by liphistius** [PaulWoitaschek/MaterialAudiobookPlayer#359]
Steps to reproducing the error:
1) Pause
2) Close app
3) Clear Ram
4) Open player (time mark is at the correct time, 5h in)
5) Push play
6) Player skips to the beginning of the file (time mark is not at the correct time, 1m3s in)

Device: Redmi Note 2
Chipset: Mediatek MT6795 Helio X10
CPU: Octa-core 2.0 GHz Cortex-A53

Notes:
It's not the audio files
Works on Huawei P8 lite

Thank you for developing this audio book player and the active development.
You're doing a service to humanity.

**Comment by PaulWoitaschek** [comment]
Can you reproduce this with app 2.4.4?

If so please re-open.

**Comment by liphistius** [comment]
The bug was fixed in version 2.4.4 but occurs again in subsequent, later versions.
