### ISSUE TITLE
Endless Spinner

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/MaterialAudiobookPlayer#360]
By mail:

> When starting MAP,  i get the 'title bar' ie with Material Player, play button, preferences etc. But main screen where audiobooks are displayed is just white with the circular animation signifying the app is busy. After about 30secs of this, app crashes.

> However, if while the animation is going i press play icon (to continue playing a book) it displays the book screen. If i then go back to main window, audiobooks are displayed as normal.

>I have tried clearing cache, and then also clrared data and respecified my audiobook folder. App is ok until you exit and then open again - then back to white main window and circle animation.

**Comment by yaymeh** [comment]
Can confirm that - almost the same here, probably since 2.4.3.2 (it used to work fine until very recently). Problem is triggered again every time when rotating the screen while the book list is displayed (using the workaround described by PaulWoitaschek).

**Comment by rthorp** [comment]
I reported this bug to Paul.
Can confirm with latest 2.4.4 update that it is fixed.

However, after first installing update, it kept crashing on startup. Had to clear cache and data, then start and respecify my audio book folder.
Now it is working fine.

Thanks Paul.

**Comment by PaulWoitaschek** [comment]
Sorry for that mess.
If this happens again please re-open!
