### ISSUE TITLE
Crash on play 

### ISSUE THREAD

**Issue by kailashkalyani** [PaulWoitaschek/MaterialAudiobookPlayer#361]
On Android 4.4.2 Huawei Honor 3C
All my audio files are on the SD card. Every time I choose a file to play, the player starts playing and crashes. On crashing, I get the usual message saying Report. As long as I don't click on anything the audio continues to play.

**Comment by Ph1b** [comment]
Which version are you using? 

Did you enable automatic crash report in settings?

**Comment by kailashkalyani** [comment]
H Paul,
Thanks for the prompt follow up. I installed f droid yesterday and tried
using material player again. It works fine now. I'm confused because this
issue has plagued me since I upgraded to Android 4.4 approx 3 weeks ago.
I hadn't enabled crash reports in the settings but will do so asap.
Thanks again,
Kailash

**Comment by PaulWoitaschek** [comment]
Should be fixed as of 2.4.4. Else please reopen!
