### ISSUE TITLE
Player always stops after a few minutes

### ISSUE THREAD

**Issue by ssaring** [PaulWoitaschek/MaterialAudiobookPlayer#363]
First of all, thanks for this great audio book player!

Since the update to version 2.4.3.2 I have problems with the player, it always stops playing after about 3 to 6 minutes. Mostly I use it together with the Sleep Timer, but it also stops without it. Earlier versions of Material Player never had this problem.
I assume that the app was crashing, but I don't see any crash or report dialog. The app was just closed.
The player runs on a Nexus 5 with Android 6.0 (clean install, no update).

**Comment by PaulWoitaschek** [comment]
Thanks!

Can you reproduce this on 2.4.4?

**Comment by Jimmyc2570** [comment]
Unfortunately, material player has stopped.   I get this message every time I try to open the app.  Started last night.   Samsung Mega. Model sgh-1527 android version  4.4.2, updated player to latest version last night, no change.

**Comment by ssaring** [comment]
I've tried the new version 2.4.4  a few times and it does not crashes anymore (Nexus 5, Android 6.0.1). Thanks for the fast bugfix!

**Comment by brokkr** [comment]
I started seeing the same with the previous version and I'm still seeing it with 2.4.4. I have rebooted the phone and done some testing.

After a few minutes (2-4) of playback a popup will come up saying "Unfortunately Material Player has stopped" but playback continues. If I click OK (the only option) playback stops. I I ignore the popup (which steals focus and so doesn't allow me to interact with the phone in any other way) playback will continue for a couple of minutes (up to around 10) before ceasing. 

That is if the screen is on. If the screen is off and the phone locked, playback will simply stop after 2-4 minutes with no notice.

Some variation on this happened every time I attempt playback in the last couple of days with no exception.

Phone: Galaxy Nexus
OS: CyanogenMod 11

**Comment by ssaring** [comment]
Interesting. I can confirm that I still had no problems after 2 days of using the version 2.4.4 on my device.

**Comment by brokkr** [comment]
Also: playback is not a prerequisite. The exact same* behaviour will happen while Material Player is running but not doing anything. 

* Apart from the playback stopping/playback continuing, obviously.

**Comment by brokkr** [comment]
@ssaring I upgraded thinking - without consulting github/internet - that this would be the fix. I just checked f-droid and yes, I am running 2.4.4. @PaulWoitaschek F-droid does allow me to downgrade to 2.4.3.2 and 2.4.3 (but apparently that's it) if it's any help in testing.

**Comment by brokkr** [comment]
I coulnd't find any configuration, so I uninstalled and then reinstalled the app (still v. 2.4.4) and that seems to have fixed the problem.

**Comment by ssaring** [comment]
The problem has never appeared again in the updated versions, this issue can be closed.
