### ISSUE TITLE
Apps keeps crashing at startup

### ISSUE THREAD

**Issue by Newmooon** [PaulWoitaschek/MaterialAudiobookPlayer#364]
I've upgraded MAP to version 2.4.3.2 and it keeps crashing at startup.
I've already sent feedbacks report cause it was enabled.
Tried closing and restarting the app. Also uninstalling and reinstalling.
I've switched to version 2.4.2 (probably the one I was using before the update) and it works fine.
I'm on Android 4.0.4 on a Sony Xperia Tipo.

The apps keeps crashing after some seconds after I've opened it. I was able to reach the "set audiobooks folder" and to select the folder but after some seconds it keeps prompting the "send feedback" screen and closes itself.

**Comment by PaulWoitaschek** [comment]
Should be fixed as of 2.4.4
