### ISSUE TITLE
Cannot play OGG files after the last update

### ISSUE THREAD

**Issue by nvx2004** [PaulWoitaschek/MaterialAudiobookPlayer#365]
After the last update available at the Play Store (around 16 Dec) the application can no longer play OGG files even though they can be opened in other players without any issues. What is more, before the update I was listening to the respective audio files with Material Player and encountered no problems whatsoever. As for MP3 and MP4/AAC files, these are not affected.

It does not matter whether the files are stored in the device itself or on an SD card. If the file in question is OGG then the app shows an error message stating that "The file cannot be opened, it may be corrupted" (or something in this vein).

Thanks for investigating this issue.

**Comment by bitinerant** [comment]
I can confirm this.  I updated version to 2.4.4.1 via F-Droid and can no longer play my OGG files, which is most of them.  I tried reverting to 2.4.4 in F-Droid but it fails, even after reboot.  The error message is, "Defect file" and "The following file may be corrupt:".  As nvx2004 says, the OGG files play fine in VLC.

**Comment by PaulWoitaschek** [comment]
Should be fixed in latest versions.
