### ISSUE TITLE
Rectangular book cover option, not square only please

### ISSUE THREAD

**Issue by billyj80** [PaulWoitaschek/MaterialAudiobookPlayer#366]
Hi,

Is it possible to make option to chose shape of book cover?

Like on this screen:
http://postimg.org/image/jnixhi3yv/
Rectangular shape would match book covers better:
http://postimg.org/image/wga7l8y7b/

Maybe you can make some visual improvement to notification screen:
http://postimg.org/image/emfyjmvx1/

I have designed some icons to be used as app icon you might be intrested, in line up with material design launguage. I prepared them for Listen Audiobook Player, but author of the app is busy with other projects right now and have no time to update his Player to material design.Let me know I can share icons with you.

**Comment by billyj80** [comment]
I forgot icons screenshoot:
http://postimg.org/image/y3i63qaeh/
blue and red icon at top.

**Comment by PaulWoitaschek** [comment]
Discussed already.
