### ISSUE TITLE
No support for Android 4.04?

### ISSUE THREAD

**Issue by Thomas-O** [PaulWoitaschek/MaterialAudiobookPlayer#369]
I uninstalled MAP after the 2.4.3.2  update crashed at launch. I decided to wait until the problem was fixed and then reinstall. Now a week later the Play Store reports that my (Android 4.04) devices are no longer compatible. Is this a temporary glitch or are you dropping support for older OS?

**Comment by PaulWoitaschek** [comment]
That might be the plan. How ever as of now I fallback to an older version with some fixes applied so you should be able to install it on your phone.
