### ISSUE TITLE
Material Player "Stopped" at second startup after a folder is selected

### ISSUE THREAD

**Issue by hackabytegithub** [PaulWoitaschek/MaterialAudiobookPlayer#370]
After upgrading to version 2.4.4, the application would start normally initially and will continue to do so until after an audiobook folder is selected. At this point, it would still run normally until after the application is closed and removed from memory / background process.

Launching the application afterwards will result in a Material Player is "Stopped" soon after launching the application. This can be resolved by deleting the data and cache and the cycle can be repeated (i.e. as described from the first paragraph above.

I have also tried with smaller folders (i.e. less files) and shorter filenames, but it does not seem to have any effect. For the time being, I have reverted to version 2.4.2 which does not exhibit this error.

**Comment by hackabytegithub** [comment]
Additional information that may be helpful:
Samsung Note 3 LTE SM-N9005 running Android 5.0 (stock ROM)

Tested the latest version 2.4.4.1 and observed the same error as described in the first post above.

Not sure if this is helpful or related but I observed that in version 2.4.4.1, after playing an audiobook, the progress is saved and showed in the player view but not reflected in the list view of all audiobooks. Unfortunately, on second launch, Material Player is Stopped on startup, so I cannot see if the progress is updated accordingly in the list view. This behaviour was not observed in 2.4.4, which is strange considering the minor code change.

**Comment by irregularisnotrandom** [comment]
I get this issue too on and 4.1

**Comment by PaulWoitaschek** [comment]
Should be fixed as of 2.5.0.5

**Comment by hackabytegithub** [comment]
I had just tested 2.5.0.5 and I regret to report that Material Player still Stops on its second startup as per the first post and the playing progress is not updated in list view as per the second post.

**Comment by hackabytegithub** [comment]
I have updated to 2.5.0.10 and I'm pleased to report that the issues in this report have been fixed. Thanks you.
