### ISSUE TITLE
Feature Request: Popup window with sleep times

### ISSUE THREAD

**Issue by obsref** [PaulWoitaschek/MaterialAudiobookPlayer#372]
Hi!

I tend to vary my sleep times quite a bit when listening to audio books depending on how tired I am at the moment (don't want to miss too much).

Audible has a nice feature for this, when you hit their sleep timer you get a small popup with a few different amounts to choose from and I'd love to see this feature in MAP as well instead of having to go into settings and change the sleep timer there every time. And maybe an option somewhere to select what different times to show in the popup?

This is how it looks in Audible:

![screenshot 18 dec 2015 09_33_09 201509_33_09](https://cloud.githubusercontent.com/assets/16347928/11892674/b8392920-a56a-11e5-88ed-d6114213c3cc.png)

**Comment by PaulWoitaschek** [comment]
I believe most people are fine with a fixed amount of time they need to find to sleep.
