### ISSUE TITLE
Material Player Access Storage Permission on Marshemello

### ISSUE THREAD

**Issue by kwiromeo** [PaulWoitaschek/MaterialAudiobookPlayer#374]
The application is having some problems on my phone.

I upgraded to Marshemello recently. When the application requests access to storage, I want to grant access to it but it says that I need to change settings about apps that draw over other apps.
I am not sure that I should disable that permission from all the other applications in order for storage to work.

**Comment by PaulWoitaschek** [comment]
Do you use a screen dimmer or sth like that? If so please disable this as there are security restrictions in the android OS that disallow a screen overlay when trying to press security or permission related buttons.

**Comment by kwiromeo** [comment]
Yeah. I did. Removed the overlay and that helped my other apps.
Thanks for the tip
