### ISSUE TITLE
2.5 binary size went up from 2.7 mb to 29 mb?

### ISSUE THREAD

**Issue by gerroon** [PaulWoitaschek/MaterialAudiobookPlayer#379]
Hi

The most recent binary on Fdroid is like 29mb. Is that normal? That is quite a jump which can be very limiting on low end android devices. 

thanks

**Comment by PaulWoitaschek** [comment]
That was an experiment. I don't know why fdroid picked that version up.

**Comment by digital-carver** [comment]
Something similar to this seems to be going on again. The currently suggested F-Droid build (5.0.2) is 72.7MB in size. The previous version 5.0.1, which is on Play Store and there shows with size as 3.0 MB, shows up on F-Droid as being 85.8 MB.

**Comment by gwarser** [comment]
https://github.com/PaulWoitaschek/Voice/issues/978
