### ISSUE TITLE
Feature Request: End the playback after current file

### ISSUE THREAD

**Issue by Lisnarsil** [PaulWoitaschek/MaterialAudiobookPlayer#382]
Hi
It would be great to have an option that allows to end after the current file has finished.

**Comment by PaulWoitaschek** [comment]
Duplicate #80

**Comment by eevleevs** [comment]
I can't see that this has been implemented on #80. 

I would also like to stop at the end of every file, and I would appreciate it to be a fixed setting, not to be activated every time. Thanks!
