### ISSUE TITLE
Cant select external sdcard after updating to android m

### ISSUE THREAD

**Issue by vityas-off** [PaulWoitaschek/MaterialAudiobookPlayer#383]
I can only select "0" and "sdcard" which both links to /sdcard, but my sdcard (not formatted as internal) now on /storage/S0ME-NUMBER
![screenshot_20151231-021153](https://cloud.githubusercontent.com/assets/15840124/12059633/9661166c-af67-11e5-8d3c-49a66bc02955.png)

**Comment by aperomsik** [comment]
I have the same problem... and I don't even see the storage selector.
