### ISSUE TITLE
too much disk activity

### ISSUE THREAD

**Issue by irregularisnotrandom** [PaulWoitaschek/MaterialAudiobookPlayer#384]
Hi

I was warching my logs to see why my battery was draining. And i see that MP scans folders everytime it startd up, rescans everytime it is activited(fg process) and when i leave the app.

Maybr this is reasonable when you have a book or two but it can be an issue for people with many books(battery wise). I feel like it shoukd only rescan if it detecs any change.

I Am using 2.4.2.2

**Comment by PaulWoitaschek** [comment]
Duplicate #299
