### ISSUE TITLE
audio corruption on seek

### ISSUE THREAD

**Issue by kevmitch** [PaulWoitaschek/MaterialAudiobookPlayer#386]
#195 seems to have resurfaced and is present in v2.5.0.5. It seems that the code has changed radically since then now using the Exoplayer, so I'm not sure what the codec.flush() equivalent is.

**Comment by PaulWoitaschek** [comment]
ExoPlayer turned out to be quite buggy.

At the moment we use the [AntennaPod Audio Player](https://github.com/AntennaPod/AntennaPod-AudioPlayer) which uses the same initial implementation.

Can you report it upstream?

**Comment by kevmitch** [comment]
This is fixed for me as of  2.6.0.1
