### ISSUE TITLE
Player forgots last position after sleep

### ISSUE THREAD

**Issue by ahajda** [PaulWoitaschek/MaterialAudiobookPlayer#387]
When I pause playback and phone enters sleep mode (purging apps from memory,  I suppose). After that when I stat player again and choose the last book it shows the last position correctly, but when I press play button it jumps to different position in the book, always much earlier that the correct one.
Material Player 2.4.2.2
Android 5.0.2

**Comment by ahajda** [comment]
One more thing, it happens with long files, in my case duration of file is 42 minutes and everything works OK if the position is below 9:16.

**Comment by PaulWoitaschek** [comment]
Can you seek within the file normally?

**Comment by ahajda** [comment]
Yes, I can, either choosing arbitrary location on seekbar, either using skip button.
I have tested it on MP 2.5.0.5, the same behaviour.
Could it be caused by integer overflow like in https://github.com/google/ExoPlayer/issues/326 ?
Below suspicious logcat when seeking for about 20th minute of mp3 ends at 1:17:

D/MP3Extractor( 4451): before getFramePos seekTimeUs=1200088000
D/TableOfContentThread( 4451): getFramePos--TargetTimeUs=1200088000,tableTimeUs=87768000,bMandatory =1
D/TableOfContentThread( 4451): getFramePos--mTocInterval=32,mEntryCount=115
D/TableOfContentThread( 4451): difftime >8min seek::curpos=603808,nowTs=87552000
D/MP3Extractor( 4451): after seek mCurrentTimeUs=87552000,pActualPos=603808

**Comment by PaulWoitaschek** [comment]
Is this still present with the latest version?

**Comment by ahajda** [comment]
Yes, it is still present. v.2.6.0.1

**Comment by PaulWoitaschek** [comment]
If this is still present in the latest version please comment and I'll reopen.
