### ISSUE TITLE
Feature request: Disable bluetooth on sleep

### ISSUE THREAD

**Issue by em-a-il13** [PaulWoitaschek/MaterialAudiobookPlayer#391]
HI,

I listen to audiobooks with a bluetooth audio connection.
It would be very useful to disable bluetooth after sleep timer has stopped playing audio. 
Would be very good to save battery.

Hopefully thats not to hard to code. Thanks.

**Comment by PaulWoitaschek** [comment]
I think this would only be useful for a very little amount of users and thus I prefer to keep the structure simple.
