### ISSUE TITLE
Play/Pause stopped working on the Pebble

### ISSUE THREAD

**Issue by benthor** [PaulWoitaschek/MaterialAudiobookPlayer#392]
The Pebble smartwatch comes with a sort of "remote control" app for Android. Using this app, I used to be able to play/pause and skip forwards/backwards in the Material Player. This worked great for a while.

Then I got a new phone (Android 6 versus Android 4 previously) and also got up-to-date versions of the Material Player and the Pebble support-app. Everything continues to work great, and I can now even see a "book progress" bar on the watch, along with an indicator if MAP is currently in "Play" or in "Pause" mode.

However, (apart from the volume controls) the app on my pebble can no longer control play/pause/forward/rewind for MAP _at all_. (The same still works with VLC and all other players I have tried)

I do not know where the issue comes from, because I've upgraded basically every component along the way. I however see a chance that the bug was introduced into a recent version of MAP (because all other players continue to work great)

I am using MAP version 2.5.0.7.1, Android version 6.0.1 (Google Nexus 5), and Pebble app version 3.8.1 and Pebble firmware version 3.8.2

**Comment by PaulWoitaschek** [comment]
Same problem on [AntennaPod](https://github.com/AntennaPod/AntennaPod/issues/1466).

Does it work for you there?

**Comment by daniloriccitelli** [comment]
Same for me.i just started to use MAP, and went to use the pause/play from my pebble.but didn't work
(although the volume buttons work well).
Out of curiosity I have tried Smart Audiobook Player, and there the controls work ok.but i still like MAP with its beautiful material design, so i will stick with it until the issue is resolved.
I am running Nexus 5 with android 6.0.1, Pebble Classic (App: 3.8.1-942-b60f188, Watch: v3.8.2).
Hope it helps.

**Comment by PaulWoitaschek** [comment]
Can you check [this app](https://play.google.com/store/apps/details?id=lt.andro.broadcastlogger) and tell me what the outputs are when you press your pebble buttons?

It basically monitors all system events and I expect pebble to send one we don't react to.

**Comment by benthor** [comment]
Just downloaded and tried AntennaPod. Indeed, it has the same issue.

I installed the broadcast logger but it does not produce any relevant output when I press the pebble buttons. Not even when I (successfully) change the volume or (again successfully) control VLC. (I am sure that the logger works correctly because it keeps reporting changes in WiFi signal intensity and battery charge)

**Comment by benthor** [comment]
(The volume buttons built into my phone don't produce system events either)

**Comment by benthor** [comment]
(Headset plug in/out DOES generate a system event however)

**Comment by PaulWoitaschek** [comment]
It might be easiest if you just ask the pebble guys.

**Comment by benthor** [comment]
I just sent an issue report to the pebble people but my hopes aren't high.

However, stabbing in the dark, I may have found a possible avenue to investigate:

Looking at the [AndroidManifest.xml](https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/AndroidManifest.xml) of [VLC-Android](https://code.videolan.org/videolan/vlc-android) and comparing it to [that of MAP](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/audiobook/src/main/AndroidManifest.xml), the following stands out:

VLC-Android makes use of a [RemoteControlClient](http://developer.android.com/training/managing-audio/volume-playback.html) Receiver where MAP only uses the (apparently outdated) MediaButton Receiver. The same is true for [AntennaPod](https://github.com/AntennaPod/AntennaPod/blob/develop/app/src/main/AndroidManifest.xml) as well.

Worth investigating?

**Comment by benthor** [comment]
I got the following reply from Jon Barlow from Pebble Developer Support

> Hi benthor,

> I had this response from the Android team:

> If a player has a media receiver (for Intent ACTION_MEDIA_BUTTON) and also has an ongoing notification during playback, then we will probably forward media key control Intents to it - but that's effectively legacy control support; the best way to be controlled by Pebble is to implement a http://developer.android.com/reference/android/media/session/MediaSession.html                                                             

> I hope this helps!

> Kind regards,

> Jon Barlow
   Developer Advocate

Is this useful?

**Comment by PaulWoitaschek** [comment]
> VLC-Android makes use of a RemoteControlClient Receiver where MAP only uses the (apparently outdated) MediaButton Receiver (which is true for AntennaPod as well).

RCC is deprecated, so it's other way around.

> the best way to be controlled by Pebble is to implement a http://developer.android.com/reference/android/media/session/MediaSession.html

That's what [we do](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/kotlin/de/ph1b/audiobook/playback/BookReaderService.kt#L102) already.

**Comment by benthor** [comment]
> That's what [we do](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/kotlin/de/ph1b/audiobook/playback/BookReaderService.kt#L102) already.

While it looks like it shouldn't really make a difference, it seems like you are using [MediaSessionCompat](http://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.html) instead of [MediaSession](http://developer.android.com/reference/android/media/session/MediaSession.html) in that code. Not sure if that is relevant or not.

**Comment by PaulWoitaschek** [comment]
Can you check [this version](https://www.dropbox.com/s/ekcu6pu20noagjc/pebblefix.apk?dl=0)? It handles the input events a little less strikt. I.e if the first event sent is not a Down event this should be handled now as well.

**Comment by benthor** [comment]
It works! Play/pause, skip forward/back, everything!

**Comment by PaulWoitaschek** [comment]
Great!

Stupid Samsung bug again ;-) They notify you with a `AUDIOFOCUS_GAIN` even if you did not gain it as you already had it. Why does Samsung always have to modify systembehavior so its opposite to the rest of the Android world? :-1:
