### ISSUE TITLE
Multi-file books sometimes repeat chapters

### ISSUE THREAD

**Issue by amorrn** [PaulWoitaschek/MaterialAudiobookPlayer#395]
Since 2.5.0.7.1, I noticed that audiobooks that are split into multiple files occasionally have an issue where at the end of a file it will start replaying the finished file instead of changing to the next onein the book. If I hit the next button, the file queues up just fine. I'm on LP 5.0. The issue is intermittent, sometimes the chapters switch as expected.

**Comment by PaulWoitaschek** [comment]
* Are there others that face this?
* How often does it work false in percentage?
* **is it reproduceable with some files**?
* **If so can you <a href="mailto:woitaschek@gmail.com">send me</a> such a file**?

**Comment by amorrn** [comment]
I've tried reproducing it with the files that exhibited the behavior. They
transitioned OK. By percentage I'd say roughly 10% of the time. In the 12
files I've listened to of this book it's happened twice on 2.5.0.7.1. If I
can find a file that reproduces it reliably I will send it to you. In the
meantime I've downloaded the latest version on F-Droid, will let you know
if the issue recurs.

**Comment by tuomas2** [comment]
I also have had this at least twice.

**Comment by PaulWoitaschek** [comment]
I think this should be solved as of one of the latest versions.
If you face this again, please comment here.
