### ISSUE TITLE
Maintain aspect ratio of artwork

### ISSUE THREAD

**Issue by etnoy** [PaulWoitaschek/MaterialAudiobookPlayer#397]
Hey! Love this app. A minor nitpick I have is that the artwork is stretched to a square aspect ratio. Would it be possible to turn it off, so that the artwork fills the square space, with the aspect ratio unchanged? That would make it neater :)

**Comment by synergeticink** [comment]
Nice! I downloaded the app and noticed the same issue. Came here to report it. Thanks

**Comment by PaulWoitaschek** [comment]
Are you talking about the images MP directly fetches at startup from the files?

**Comment by etnoy** [comment]
I don't know enough of the inner workings of MP to say when it fetches the artwork, but I'm talking about the thumbnails you see on the "main" screen, i.e. the list of all books. Is that clear enough?

**Comment by bigwoof** [comment]
Seems to stretch images to 1x1 ratio if they come from the folder containing the audio files

**Comment by Cormak** [comment]
I'd like an option to fill height as well. Non-square images seem to get cropped.
