### ISSUE TITLE
Feature: Broadcast audio stream to upnp device

### ISSUE THREAD

**Issue by tuomas2** [PaulWoitaschek/MaterialAudiobookPlayer#398]

**Comment by PaulWoitaschek** [comment]
I assume this is not trivial. 

Please use one of the apps out there that can stream upnp on a global level.

**Comment by tuomas2** [comment]
I'm not sure if it is trivial or not, but many players implement this, so it might not be that difficult. Maybe there is some standard way of implementing this, with some library etc? But maybe you know better.

There is of course BubbleUPNP (and maybe others) that allow broadcasting upnp general audio stream from android (i.e. from any app), but those require root, which is not (always) feasible.
