### ISSUE TITLE
Transifex update

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/MaterialAudiobookPlayer#402]
Update translations and collaborators.

**Comment by Helderjfl** [comment]
Where the string "all', key "storage_all" is used on the app?

**Comment by PaulWoitaschek** [comment]
There is a dropdown on the top right of the file picker.
There it says "All" to show all the storages available.

That is for a hotfix as it is not possible to show all the marshmallow storages.
