### ISSUE TITLE
Can't access internal storage in Marshmallow on Nexus 7

### ISSUE THREAD

**Issue by aperomsik** [PaulWoitaschek/MaterialAudiobookPlayer#404]
Running cm13 on 2012 Nexus 7... Material Audiobook Player asks me to choose a folder, I click the + button, then the folder selection screen is almost completely blank. I did grant storage permission when requested.

**Comment by PaulWoitaschek** [comment]
Still happening after restarting the app?

**Comment by aperomsik** [comment]
Tried several times with no luck. Finally after "force stop" it seems to work on the "owner" account, but still didn't help on the restricted account. Reboot didn't help either.

**Comment by PaulWoitaschek** [comment]
Don't know about restricted account but maybe he is not allowed to get the permission?

**Comment by aperomsik** [comment]
It's working on Orpheus.

**Comment by PaulWoitaschek** [comment]
Which version are you using? What means Orpheus?

**Comment by aperomsik** [comment]
Material Player 2.5.0.10 from Google Play. Orpheus is an open source music player. https://github.com/OpenSilk/Orpheus

**Comment by PaulWoitaschek** [comment]
So this looks more like a cm bug to me. For other people it works - as well as on my emulator.

**Comment by PaulWoitaschek** [comment]
I have an idea of a fix for these cases:

After getting the permission, and if a read still can not be performed, a process restart with [ProcessPhoenix](https://github.com/JakeWharton/ProcessPhoenix) can be performed with the saved state set in the intent.

**Comment by PaulWoitaschek** [comment]
I think this is covered with the solution provided in #349 .
