### ISSUE TITLE
Material Player blocks media buttons for all other applications ( Marshmallow / CM13 )

### ISSUE THREAD

**Issue by yaymeh** [PaulWoitaschek/MaterialAudiobookPlayer#406]
Tested with 2.5.0.7.1 and 2.5.0.8 on CM13 and to a lesser extent Marshmallow.

Similar to the issue described here:
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/issues/290
But the workaround (reboot) isn't working any more: 

Even with the widget removed and after a reboot, while a different (/music) player is already running, material music player starts up and starts playing when a "play" media button is pressed (tested with blue-tooth car stereo and with wired head phones). Swiping away the notification does nothing - it just reappears every time a media button is pressed. 

Blacklisting "audio focus" for material music player does not change this behaviour. 

The only way to listen to music in my car is to completely uninstall material audiobook player and reinstall it later. 

Tested several different audio / video players while material audiobook player was not installed, did not have any problems switching between them or choosing which one my car radio buttons controls. 

**Edit:**
Found another player that seems to work as intended together with material audiobook player: ch.blinkenlights.android.vanilla 1.0.36
And it ALSO happens to block all other audio players from using the media buttons when it's installed.

Does that mean I should take this back upstream? (was asking around in IRC a few days ago, but they sent me "downstream", because the other audio apps didn't have / make those problems )

**Comment by yaymeh** [comment]
I'm in way over my head there, but as far as I can tell, there seem to be to be conflicting media button mechanics (AOSP music player + lots of other apps vs documentation + demo apps?) used upstreams for marshmallow / CM13. 

Looks like - depending on which one will be considered to be "broken" and which one will subsequently be "fixed" - either material player will be among the first ones to do it right the "marshmallow way"... or one of the few ones that break permanently. Have not been able to figure out which one, maybe noone knows.

**Comment by PaulWoitaschek** [comment]
Do you know what excactly is taking the audiofocus from a development point of view? 

We are using [MediaSessionCompat.setActive](https://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.html#setActive(boolean)) to stop getting the focus so I'm wondering what excactly is happening here.

**Comment by yaymeh** [comment]
Oh, looking at some of that "media session" stuff again helped, thanks!

After making a huge mess and installing a lot of random apps I noticed that all the apps that work while the audiobook player is installed do either support media sessions too (there seem to be relatively few of those around that are open source?) OR have their button receiver priority set to 999 for some reason (weird...).

After setting priority of all apps that were unable to receive media events to 999, they now all work at the same time (I guess I should have played around with that sooner, but I thought the "button priority" had been retired ages ago :/ )

Guess that means there's really something broken with media sessions somewhere upstream? I should probably wipe everything and try again in a clean environment just to make sure that I didn't change / do anything else weird when I messed with the manifests and recompiled random stuff...

**Comment by PaulWoitaschek** [comment]
This one was a little tricky.

Googles recommended way of requiring to add the intent filter to the service leads to the service always receiving all the events.

I changed that behaviour and set a regular `BroadcastReceiver` in between that just forwards the events to the Service.

27201ce574f5fe211d91bbbca6f7a8f3a5e83850

Please test it, but it should work. Now it just catches events when the notification is there. Once you swipe it away, it won't receive any further events.
[109-preview-audiobook-debug.apk.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/134237/109-preview-audiobook-debug.apk.zip)
