### ISSUE TITLE
Shake to reset sleep timer

### ISSUE THREAD

**Issue by Phytophthora** [PaulWoitaschek/MaterialAudiobookPlayer#407]
I like the design of MAP but the feature I use most in other audibook players is missing here:
Use the motion sensor to reset the sleep timer.

**Comment by PaulWoitaschek** [comment]
There are too little users for a setting and its too unintuitive to make it a default.

**Comment by deoren** [comment]
For what it is worth I'd use this feature if it were added.

**Comment by allmynamesweretakenomoreideas** [comment]
This is the most intuitive function ever! Everybody trying this will confirm. Please reconsider.
