### ISSUE TITLE
Kodi integration?

### ISSUE THREAD

**Issue by Thomas-O** [PaulWoitaschek/MaterialAudiobookPlayer#410]
Hello,

I play my audiobooks both within your application and also via dedicated Kodi / OpenElec devices using the [Audiobook](https://github.com/robwebset/script.audiobooks) add-on. I sync a library of audiobooks between my PC, smartphone and the devices using Syncthing and BtSync. It would be fantastic if I could also sync a text file with playback positions. So that I can play an audiobook on a mobile device when out and about; later picking up where I left off on a Kodi / OpenElec TV or hi-fi.

I was wondering if you'd consider working with the developer of the Kodi application. Perhaps creating the default and universal structure for audiobook position text files. The text file stored in the same folder as the audiobooks or in a folder chosen by the user. Allowing for an easy integration between the two applications and possibly between new as yet to be developed applications.

Thanks for your time. And thanks very much for the excellent application.

_Thomas_

**Comment by PaulWoitaschek** [comment]
I do not want to have a file soely for Kodi as I think this would benefit not so many.
However when Dropbox sync, etc comes one day, this can be a sub feature.

**Comment by PaulWoitaschek** [comment]
#229
