### ISSUE TITLE
Does faster playback speed use more battery?

### ISSUE THREAD

**Issue by hub2git** [PaulWoitaschek/MaterialAudiobookPlayer#411]
In some apps, playing at a speed other than 1.0X drains the battery quicker. What about with Material Audiobook Player?

**Comment by PaulWoitaschek** [comment]
Yes, in some cases the playback speed causes some overhead.

Some measurement was performed [here](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/issues/215) by @kevmitch . If you want detailed stats on what happens at others speeds I think it is easiest if you measure yourself.
However if it comes with increased power consumption I assume there is not much to do against it.
