### ISSUE TITLE
Rewind button looks weird

### ISSUE THREAD

**Issue by rafaeln** [PaulWoitaschek/MaterialAudiobookPlayer#413]
Version 2.6.0.1 from Play Store. But it was already looking like this on 2.5.0.8 from F-Droid

![screenshot_2016-02-17-10-02-58](https://cloud.githubusercontent.com/assets/2940362/13113642/e1ba7920-d55d-11e5-95ae-fe6175041890.png)

**Comment by PaulWoitaschek** [comment]
Thanks. Can you check if this fixes it for you?

[111-2016-02-07-nightly2-audiobook-debug.apk.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/134756/111-2016-02-07-nightly2-audiobook-debug.apk.zip)

**Comment by rafaeln** [comment]
This does indeed fix it for me.
