### ISSUE TITLE
Enable sleep timer automatically between T1 & T2

### ISSUE THREAD

**Issue by NeuroNex** [PaulWoitaschek/MaterialAudiobookPlayer#414]
Add new option "**Enable Sleep Timer automatically**" : Checkbox
If checked, then there are some more parameters:
Time interval to enable sleep timer:
- Start Time: (default midnight)
- End Time: (default 6:00 am)
- Sleep timer duration: (default 30 minutes)

I find this option very practical. Hope that you will like it. Thanks for any consideration.

**Comment by PaulWoitaschek** [comment]
Thanks for the suggestion. I think it is not too complicated to just press play and then sleep. That way we can get rid of one setting.

**Comment by eevleevs** [comment]
It is not possible to press sleep if you are controlling the playback via Bluetooth. Please reconsider this.
