### ISSUE TITLE
Audible aax support?

### ISSUE THREAD

**Issue by nullnullnix** [PaulWoitaschek/MaterialAudiobookPlayer#415]
Hi. 
Will it be possible to implement .aax as supported file types? 
If not possible, pls let me know. 

Thx a lot.

**Comment by andrewjmetzger** [comment]
@nullnullnix Unfortunately, Audible's.AAX format is proprietary. In order  to play.AAX files, the official app is needed. Solutions exist to convert these to MP3. I will post some later!

**Comment by andrewjmetzger** [comment]
Here is a program which will allow the conversion of .AAX to .MP3 files. [Audible AAX to MP3 Converter](https://sourceforge.net/projects/aaxtomp3/). The Audible Manager and a Windows PC are also required for the conversion. Click [here](https://www.audible.com/sw?pageFlowType=PC_WIZARD), then **select Download to my computer** to install Audible for desktop PCs.

Instructions on using the converter can be found on the download site, linked above.

Once converted, you may play the MP3s in Material Audiobook Player as desired.

**Comment by andrewjmetzger** [comment]
**UPDATED 2016-02-21: Instructions for a newer, more efficient software tool.** Sorry for the confusion!

# Workaround
## Notes
- Tested with Windows 8.1. Works in Windows 7 and up.
- Does not require Audible software to be installed on PC.
- This guide assumes the working directory is `%USERPROFILE%\Downloads\`
- **You will need:**
  - An Audible audiobook file (`.aax` format), saved locally
  - inAudible 1.66 (see also, the [VirusTotal scan](https://www.virustotal.com/en/file/4992bbcf671e1cef310592f13d35757611a38d209e313028db8180f90025a078/analysis/1456035250/)) : 
    - Via .torrent file: [click here to download] (http://torcache.net/torrent/13DADC3399F02E051E73F2F8CE5650A0B4E0346D.torrent), 
    - Copyable magnet link: `magnet:?xt=urn:btih:13DADC3399F02E051E73F2F8CE5650A0B4E0346D&dn=inaudible+v1+666&tr=udp%3A%2F%2Ftracker.istole.it%3A80%2Fannounce&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce`
    - Direct link: [Click here](https://s3.amazonaws.com/overture/pub/inAudible+v1.666.msi) to download at Amazon S3.

## Steps
1. Within inAudible, locate the Audible Files field. **Click the ... button**, then select a book to add. _If desired, inAudible can automatically create create subdirectories for each autor and/or book: **click More Options** then, under Output Options: Create Folder Structure..., check **Book Title**, **Author**, or both. The MP3s will then be found in `...\Downloads\<Author>\Book\`._
2. Under the Output Files heading, ensure **MP3** is selected. 
3. For Codec Options, choose **VBR Mode**. Then, **Drag the slider to 9**. This will maintain lossless quality, and has the potential to reduce file sizes significantly. Check the Multithreading option box if desired for a speed boost.
4. For Preprocessing Options, check **Split By Chapter Markers** and, if desired, check **Remove "Audible" clips**.
5. Finally, click **Begin Conversion** and wait. Times vary, but are generally between one and five minutes per book, depending upon length. If conversion is slow, enable Multithreading.

____

Any other questions, feel free to reply here, I am happy to help.

Regards, 
Andrew

**Comment by PaulWoitaschek** [comment]
Deleted one comment that described how to break Audibles proprietary format. Please don't discuss that herre.

**Comment by andrewjmetzger** [comment]
@PaulWoitaschek Sorry!
