### ISSUE TITLE
Playback is extremely slow

### ISSUE THREAD

**Issue by LordJordane** [PaulWoitaschek/MaterialAudiobookPlayer#416]
When I play an audio book, then pause it and clear the app from Recent, and wait for a while(more than an hour or so), and then resume playback of the audio book the sound sounds very slow and distorted. It reminds me if the infamous super fast playback issue that occurred under the same circumstances. Device in question is Galaxy Note 4 SM-N910C on CM13.

**Comment by PaulWoitaschek** [comment]
How do other players perform then?

**Comment by LordJordane** [comment]
If you mean regular music players, they work fine. Tested with Google Play Music and VLC.

**Comment by LordJordane** [comment]
So after so more testing, I found out that the old super fast playback issue has returned. It happens more frequently than the super slow playback problem.

**Comment by PaulWoitaschek** [comment]
You mean the problem was fixed for some time and then returned?

**Comment by LordJordane** [comment]
Well, no. A few months ago I had problems with the fast playback after long pause issue and seldom used the app. Recently I saw that the changelog said that the issue had been fixed. So I decided to start using the app again but got these issue.

**Comment by PaulWoitaschek** [comment]
There is nothing I can do as its hardware related.
