### ISSUE TITLE
"Unforunately, Material Player has stopped" message when attempting to bookmark location

### ISSUE THREAD

**Issue by deoren** [PaulWoitaschek/MaterialAudiobookPlayer#420]
I don't see this on all titles, but on at least two Material Player crashes immediately upon attempting to make a new bookmark entry. I have previously created bookmarks for both titles without issue.

Any tips for troubleshooting this issue? I'm going to load the affected titles on a few other devices and test there. I'll report back the results.

**Comment by deoren** [comment]
I loaded a fresh copy of the audiobook on another device and created +20 bookmarks (no crashes), although granted all bookmarks were for the same location. That "experiment" doesn't really prove much I suppose.

**Comment by PaulWoitaschek** [comment]
Its good you found it. Please don't reset the app, I need that crash ;-)

* Which version do you use?
* Did you get it from the play store? 
* Did you enable crash reports in the settings?

If you got it form the play store, there should be a report button when it says it stopped. Can you enter a custom message here so I can identify the crash? I.e(Github#420)

**Comment by deoren** [comment]
Sorry, I completely left out the obvious stuff:

* Version 2.6.0.1
* F-Droid build

After I saw your response I looked and saw that the bug reporting feature was turned off. I'll enable it and give it another try.

Thanks for your response.

**Comment by PaulWoitaschek** [comment]
What kind of phone do you have?

**Comment by deoren** [comment]
Heh, I really am forgetful. Sorry about that.

LG V10
Android 5.1.1

Assuming the F-Droid build has similar functionality, I am going to trigger a crash report in a few minutes.

**Comment by deoren** [comment]
Alright, I just had it crash, but no dialog box was given. I do have the crash report option enabled though, so hopefully something was sent.

**Comment by deoren** [comment]
I just replicated the issue on my Nexus 4 which is running CyanogenMod 13.0-20160226-NIGHTLY-mako.

As I mentioned previously, I made a bunch of bookmarks without any I'll effect. I did not however really use that device to listen to the audio book for any length of time. Tonight I listened for about 40 minutes and went to save my progress. That is when the app crashed.

I am using the F-Droid build of Material Player version 2.6.0.1.

As with the V10, I enabled bug reporting in the hope that it sends you something useful.

All of that said, do you get reports from F-Droid builds?

**Comment by PaulWoitaschek** [comment]
Still happening in the latest version? (Released 2h ago)

> All of that said, do you get reports from F-Droid builds?

Yes, if the ACRA setting is enabled.

**Comment by deoren** [comment]
> Still happening in the latest version? (Released 2h ago)

@PaulWoitaschek I'll give it a try just as soon as F-Droid releases the update (from what I recall attempting to use any other apk won't preserve existing data to confirm bug is fixed).

**Comment by deoren** [comment]
F-Droid made 2.6.0.4 available for installation yesterday. I tested it and bookmark functionality has been completely restored (for existing installations that were making Material Player crash). Thanks!

**Comment by deoren** [comment]
@PaulWoitaschek I started to close this out, but wasn't sure if you wanted to make any specific notations, assign a milestone, etc. Thanks again for the fix and for this app!

**Comment by PaulWoitaschek** [comment]
Thanks :)
