### ISSUE TITLE
System player resets the audiobook

### ISSUE THREAD

**Issue by podema** [PaulWoitaschek/MaterialAudiobookPlayer#422]
Material player correctly records the position, however when you push play button the audiobook starts from the beginning.
I will provide a video later

**Comment by podema** [comment]
Edit: bug on miui

**Comment by podema** [comment]
Check this short videos:
[material audiobook player not working](https://www.youtube.com/watch?v=7UXs2BInfrU)

I also attached a video with a music player that holds position:
[poweramp example](https://www.youtube.com/watch?v=2G5f71S6K0M)

**Comment by podema** [comment]
I think that the issue is caused because of the controls start the player somehow.
After trying lots of apps i think this issue can be fixed by adding the functionality to open (music) files with material player. 
Furthermore it's a nice feature!

**Comment by PaulWoitaschek** [comment]
* Which version are you using?
* Can you else seek / play / pause without issues?
* Do you use an emulator?

**Comment by podema** [comment]
When my android top bar says open music player the book restarts, after that the top bar controls material. Check the video again and you will see.
I can run tests or record anything if required.
I can normally use mayerial audioplayer it's only the first tap at play that restarts the book. Then i can rewind, change playback speed,  i haven't found any issue.
I'm using android 5.02 LRX22G with miui 7 on a xiaomi redmi note 2. Kernel version 3.10.6.
The app version is the one in the play store.

**Comment by PaulWoitaschek** [comment]
> The app version is the one in the play store.
And which one? There are multiple in the store right now.

**Comment by podema** [comment]
I'm running: 
https://play.google.com/store/apps/details?id=de.ph1b.audiobook
version # 2.6.0.1

**Comment by PaulWoitaschek** [comment]
Do you see this with all files or just this one?

**Comment by podema** [comment]
Is the same with all files, first time the position resets. after this i can use the player. I use a bookmark as a workaround. 
Since i discovered the issue i tried to install a clean android rom on my device (aosp) and the problem persists.

**Comment by PaulWoitaschek** [comment]
If this issue still persists please comment and I'll reopen.
