### ISSUE TITLE
Automatically import .ZIP files from web browser

### ISSUE THREAD

**Issue by Ders1** [PaulWoitaschek/MaterialAudiobookPlayer#424]
This may not be possible and/or worth the time of development.  I would like to click on .Zip files downloaded from the internet and have the option to automatically import into Material Player.  This would involve unzipping them into their own folder within the Audobook Folder.

**Comment by PaulWoitaschek** [comment]
I want to leave that task to a file manager.

**Comment by Ders1** [comment]
That makes sense for a user like you or me, but for people like my dad, I
couldn't ask them to do that. I suppose you aren't targeting that type of
user. Thanks for the response
