### ISSUE TITLE
Feature Request: Show status of audiobook in library

### ISSUE THREAD

**Issue by allmynamesweretakenomoreideas** [PaulWoitaschek/MaterialAudiobookPlayer#427]
When viewing library list, the should be a status indication for each audiobook. Weather the book is 1) unread 2) begun reading 3) finished. Could be a small symbol at the cover or different colour marks.

**Comment by PaulWoitaschek** [comment]
#338

**Comment by allmynamesweretakenomoreideas** [comment]
#338 is something different. I mean actually the information "new", "in progress" and "finished" as values stored in the database so this values are basis for managing the library. E.g. showing only "new" books. Setting on of the values manually by using context menu. Making the status indication visible on the list items Ist just one necessary feature to manage libraries with 100+ items.

**Comment by PaulWoitaschek** [comment]
Ah okay. The audiobook player is not targeting that scenario. I think its strength are when you use only up to 8 books.
Else it clearly misses core features like sub-books, sorting, etc. 

And I like that it is so concise. So sorry - no.
