### ISSUE TITLE
Skip forward on lock screen 

### ISSUE THREAD

**Issue by pbinksma** [PaulWoitaschek/MaterialAudiobookPlayer#431]
Dear Paul, 

This is by far the best player for audiobooks. I use it to hear a weekly newspaper. For this I would love to see an option to skip to the next chapter (i.e. article) on the lockscreen. Currently I am only able to rewind or skip back. 

Thanks
Patrick

**Comment by PaulWoitaschek** [comment]
Dear Paul,

It should be rewind and fast forward. I want the lockscreen to directly focus on the current audiobook. Files should not bother one and it should be only the time that matters.

I think for a daily newspaper a real podcatcher would fit better as it handles exactly these situations. Did you give [AntennaPod](https://play.google.com/store/apps/details?id=de.danoeh.antennapod&hl=de) a try?
