### ISSUE TITLE
No buttons on widget after today's update

### ISSUE THREAD

**Issue by JocPro** [PaulWoitaschek/MaterialAudiobookPlayer#432]
![screenshot_2016-03-12-20-11-02](https://cloud.githubusercontent.com/assets/16336845/13725890/2fdbaacc-e88f-11e5-933d-19ea0c3b1815.png)
Kitkat 4.4.2, Nova Launcher, 4.1 widget.

**Comment by Icy13** [comment]
I have a similar problem after the update. I have just a play button and no fast forward or rewind buttons

**Comment by PaulWoitaschek** [comment]
Should be fixed.
