### ISSUE TITLE
Feature Request: File names instead of Title / Ignore ID3 tags

### ISSUE THREAD

**Issue by joesphroth** [PaulWoitaschek/MaterialAudiobookPlayer#433]
I have some podcasts that do not have any tags so they all show as the same title and I can't distinguish between them.

Could you add a simple feature to display file names?

Thanks, great simple software!

**Comment by bitinerant** [comment]
+1 for this.  Perhaps a clear label would be "Ignore ID3 tags".

**Comment by MrSassyBritches** [comment]
this would make it so much more usable for me, i have all the dune books and its categorizing them all as Dune Saga because thats the Album tag.

**Comment by PaulWoitaschek** [comment]
#504
