### ISSUE TITLE
Skip back a few seconds feature

### ISSUE THREAD

**Issue by kdriedger** [PaulWoitaschek/MaterialAudiobookPlayer#434]
Sometimes when plugging in my phone and turning on my stereo I've missed a few seconds oh the book.  I can skip back but on books that are all one audio file it is difficult.  How about a button that skips back a bit?

**Comment by PaulWoitaschek** [comment]
> I can skip back but on books that are all one audio file it is difficult.

Why is that difficult?

**Comment by kevmitch** [comment]
> How about a button that skips back a bit?

There is, isn't there?

> Why is that difficult?

If he doesn't see the back button, he's using the slider whose sensitivity is proportional to the size of the file?

**Comment by PaulWoitaschek** [comment]
Can you post a screenshot? @kdriedger

**Comment by kdriedger** [comment]
Yes Kevin Mitchell nailed it... the slider is proportional to the length of
the file

I guess I've never wanted to click the back button because the icon on it
(to me) means go back to the beginning of the file.

Does it really mean jump back a few seconds?  If so could we pick a
different icon?  Perhaps something along the lines of:
http://www.iphonefaq.org/archives/971181

(not that I'm a huge fan of apple... don't get me wrong)

I can try this tonight as I've been using this application daily on my
commutes.

**Comment by PaulWoitaschek** [comment]
I do not understand a single word you're saying.

> Can you post a screenshot? @kdriedger

I think that would make it much clearer

**Comment by kevmitch** [comment]
@kdriedger does your screen not look like this?
![screenshot_2016-03-23-00-43-59 1](https://cloud.githubusercontent.com/assets/116549/13983620/063ca0f0-f0ae-11e5-83d8-d1958962ff6e.jpg)

**Comment by kdriedger** [comment]
Yes.  I didn't understand the double arrows.  My bad.

**Comment by PaulWoitaschek** [comment]
Oh okay. I think that's pretty much standard.

**Comment by kdriedger** [comment]
What is standard? Users not understanding the button?

Oh and thanks so much for the app.  Really loving it overall!

**Comment by kevmitch** [comment]
> What is standard? 

* `|<` and `>|` are track skip
* `<<` and `>>` are seek

this is used by all of the CD players I've owned as well as many mp3 players when they have these as separate buttons

**Comment by kdriedger** [comment]
My context was such that I was not thinking about this app as a CD Player.
It is a custom tool for listening to audio books.  i.e. my CD player does
not start at the point where I  pressed stop.  That being said, I agree
with your point and after I hear you put it in your context I feel
foolish.  Thanks for your understanding.
