### ISSUE TITLE
Feature request, report book position in stead of track position. 

### ISSUE THREAD

**Issue by bigwoof** [PaulWoitaschek/MaterialAudiobookPlayer#435]
I use my pebble watch to control material player and it displays the progress through each track on the watch, is there a way to display the overall book progress in stead as itit will be more meaningful, especially with books that have many files

**Comment by kevmitch** [comment]
duplicate #338  #294  #227 #95

on the main page where you select books switch to list instead of grid and you'll get progress.

**Comment by bigwoof** [comment]
Hi Kevin,
Sorry I don't think that I conveyed my point properly, I am referring to the progress bar that the app reports to other devices, not within the app itself - As far as I understand it is "called media progress reporting" at least according to the pebble app that I use (http://www.rebootsramblings.ca/n/musicbossforpebble/)

The pebble (and car blutooth headunit) do pick up the media progress form the app but it always shows the track progress and not the overall book progress. hopefully the media progress report can easily be switched to send the book position.  not a deal breaker - it is just a handy little feature. 

Thanks for the great app.

**Comment by PaulWoitaschek** [comment]
@bigwoof Can your pebble show two progresses?

**Comment by bigwoof** [comment]
@PaulWoitaschek no unfortunately it can only display one progress bar. I figured that it would make more sense to display the book progress as opposed to the track position.

**Comment by micressor** [comment]
+1 for this feature.
