### ISSUE TITLE
Android Auto: Update Refused

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/MaterialAudiobookPlayer#438]
Rejected with following comment:

> We found that voice commands break after two uses. Scenario: Audio is playing. User gives command. "Play chapter one". After your app confirms the command, audio will not resume, but the scrubber (line showing track progress) continues to move.
> 
> Further, when the voice button is tapped again the audio will play over the command prompt, which makes it impossible for the user to give a command, or stop the audio. This behavior would not be working from our users perspective.

Can someone confirm this? 

How does the voice command work at all? When I use it in the emulator it always responds something like:

> Don't know what you mean by 'pause music'.

I temporary removed the android auto declaration from the manifest. Does it still appear in your car?

**Comment by patrickbaumann** [comment]
I can dig into this for you. I spent a few hours trying to port MaterialAudiobookPlayer to Auto late last year and ran into the same playback control issues on the emulator and my Auto unit. I believe it had something to do with the way you've implemented your MediaSession callbacks, though I'm drawing a blank on exactly what about it led me to ditch the effort. Do you have the label or commit you built from that was rejected?

**Comment by PaulWoitaschek** [comment]
@patrickbaumann all the changes are staged. It's just the declaration that was uncommented in the manifest.

So just checkout the latest dev branch. Currently I'm in Japan without my dev machine but I'll look into what you did when I return in 30 days.

**Comment by kbolinsky** [comment]
I'd love to be able to listen to audiobooks via Android Auto - but it does not appear on the app list. I encourage you in attempting to get it working! Thanks!

**Comment by josbeir** [comment]
+1

**Comment by hoomanb** [comment]
+1 for Android auto
