### ISSUE TITLE
Even higher playback speed

### ISSUE THREAD

**Issue by sdakak** [PaulWoitaschek/MaterialAudiobookPlayer#440]
Please change max playback speed to 3x. Anything less is slow.

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/java/de/ph1b/audiobook/Book.kt#L54

**Comment by PaulWoitaschek** [comment]
#255

**Comment by sdakak** [comment]
I understand your argument about simplicity. However, please reconsider your position. I believe you are prioritizing simplicity over usability. I, and many others, regularly listen to audio books at 2.75x - 3x. I also listen to Podcasts at 3x and for this reason PocketCasts (and many other audio book apps like Smart Audiobook player) allow you to go up to 3x
