### ISSUE TITLE
feature request: libopus support

### ISSUE THREAD

**Issue by 2sam** [PaulWoitaschek/MaterialAudiobookPlayer#441]
Could you include playback support for [libopus](https://en.wikipedia.org/wiki/Opus_(audio_format))-encoded files? Opus is a very useful and practical codec for audiobooks due to its excellent sound quality for speech at very low bitrates and high compression rates. Libopus-encoded files are recognized and listed by the app but they're not actually playable, meaning the player will just skip file after file. 

Inclusion of support for those files would be much loved and appreciated
**Thank you for your excellent development!**

**Comment by PaulWoitaschek** [comment]
#31 #104 #310 #172

**Comment by 2sam** [comment]
sorry, my bad. only grepped over approved features and the first page of issues. 
still no opus support in android 6?
