### ISSUE TITLE
Freeze for some time when playing really large audio file

### ISSUE THREAD

**Issue by taiko000** [PaulWoitaschek/MaterialAudiobookPlayer#442]
When playing a 200Mb+ m4a file the play button first freezes for up to 10 seconds and touch input is ignored and then audio starts playing. After this initial delay, everything is back to normal. Android 5.1.1 AOSP Nexus 4.

**Comment by volosovich** [comment]
hello. I have the same problem with large mp3 files
Android 4.3 stock Galaxy nexus

**Comment by PaulWoitaschek** [comment]
I assume this is fixed since we switched to ExoPlayer
