### ISSUE TITLE
Low cover image resolution

### ISSUE THREAD

**Issue by allmynamesweretakenomoreideas** [PaulWoitaschek/MaterialAudiobookPlayer#445]
The cover images extracted from the Mp3 files have a poor resolution. The text on images shown in list and while playing a barley readable.

**Comment by nitro322** [comment]
Tangentially related (I'll be happy to open this as a separate request if you'd like):  would it be possible to add a preference allowing users to specify the name of an image file to use for the cover?  I frequently run into the situation where I have a couple images included in the book directory - one a hi-res cover, and one a low-res thumbnail used as a directory icon.  Material Player has a habit of using that low-res icon as the cover, which looks terrible when blown up above 32x32, and I can't get it to switch to the proper image without deleting and re-adding the entire book.  Being able to specify the image it should read first would solve that problem.

**Comment by PaulWoitaschek** [comment]
You can now chose images from disc as well as from internet.

**Comment by nitro322** [comment]
Very welcome feature.  Thanks!
