### ISSUE TITLE
Lock screen issue

### ISSUE THREAD

**Issue by visakhmv** [PaulWoitaschek/MaterialAudiobookPlayer#446]
When playing and the screen is locked the power button needs to be pressed 3 times to view the display. Pressing once wakes the display but its full black then lock again and unlocking again wakes the display properly. I'm on stock Android 6.0.1 on Motorola moto g3.

**Comment by PaulWoitaschek** [comment]
Hm from how I understand Android this is impossible to be caused by the app.
Can you check other mediaplayers and their behavior?

**Comment by visakhmv** [comment]
Well I don't have many the ones I've tried are google play music, es file explorer music player, total commander music player. None of these have this issue.
Here is an unlisted video I just made. I can remove after you've watched it [https://youtu.be/pxg4RG_NLEQ](url)

**Comment by visakhmv** [comment]
Well I don't have many audio players these are the ones I've tried. Google play music, ES file explorer, Total commander. All of these work in the background, only google and total commander has lockscreen album art.

Here is an unlisted youtube video I've just made to recreate the issue [video link](https://youtu.be/pxg4RG_NLEQ) . I can remove the video after you've watched it if necessary.

**Comment by PaulWoitaschek** [comment]
> Well I don't have many the ones I've tried are google play music, es file explorer music player, total commander music player. None of these have this issue.
Here is an unlisted video I just made. I can remove after you've watched it https://youtu.be/pxg4RG_NLEQ

Can you try [AntennaPod](https://play.google.com/store/apps/details?id=de.danoeh.antennapod)?
I know that its using the same way of displaying the album art.

Can someone else confirm this issue?

**Comment by visakhmv** [comment]
OK. the video behavior got me thinking. The issue was not with the player(sorry) it's the problem with Moto Display(a system app which shows useful icons to interact with app such as a music player without waking the display). I've black listed material player in the app and the issue is gone now.
