### ISSUE TITLE
No Sd card access on 4.2.2

### ISSUE THREAD

**Issue by gerroon** [PaulWoitaschek/MaterialAudiobookPlayer#447]
Hi

I cant select Sd card on 4.2.2

thanks

**Comment by PaulWoitaschek** [comment]
Can you post a screenshot? What's the path of your sd card?

**Comment by gerroon** [comment]
/mnt/external_sd

**Comment by PaulWoitaschek** [comment]
Can you post a screenshot?

**Comment by PaulWoitaschek** [comment]
Do you have a spinner in the top right?

**Comment by gerroon** [comment]
@PaulWoitaschek 

WHen I add a new folder, it opens in the internal sdcard and there is no way to go "up" to browse other mounts. There is only the "left" arrow on the left top and I do not see anything on the right top.

I can see the pull down mount "browser" that you are talking about on my other lollipop tablet, but not on the 4.2.2 ereader.

**Comment by PaulWoitaschek** [comment]
I added it as a fallback

**Comment by PaulWoitaschek** [comment]
Is there nothing under `/storage/`?

**Comment by gerroon** [comment]
I cant go up to storage, I am stuck at /mnt/sdcard inside MP.

**Comment by PaulWoitaschek** [comment]
And if you a file browser? Usually the stuff appears also in `/storage/`

**Comment by gerroon** [comment]
I only have sdcard0 under /storage. The external sd is listed only under /mnt
