### ISSUE TITLE
Suggestion // reset sleep timer on phone shaking

### ISSUE THREAD

**Issue by StarPicard** [PaulWoitaschek/MaterialAudiobookPlayer#448]
Hey, thank you for this wonderful app, it has rescued me my hours in the train so many days.
In this use case almost everything is perfect for me.

But I have a suggestion for the night ;) :

The app [AntennaPod](https://github.com/AntennaPod/AntennaPod) has the feature to shake the phone when sleep-timer is ending but you want to reset the sleep timer and play the stream for another _x_-minutes.

Here is the link to the specific code sections:
[AntennaPod - search: "shake"](https://github.com/AntennaPod/AntennaPod/search?utf8=%E2%9C%93&q=shake&type=Code)

Edit: Might be good to use with the sleep timer fade out #393 (shake while fade out time)

**Comment by deoren** [comment]
The combination of the two would indeed be useful (I'd certainly use it).

Two things: 

1. This is a duplicate of #407 
2. The developer (@PaulWoitaschek) rejected the feature request, but perhaps with enough interest it could be reconsidered.

**Comment by PaulWoitaschek** [comment]
@deoren Correctly. You can +1 topics. I make decisions based upon intuition / minimalism guidance and upon how many people show interest in a specific feature.

**Comment by fabsmusicjunkie** [comment]
+1
Loving this feature in antennapod

**Comment by PaulWoitaschek** [comment]
Implemented as of 16.08
