### ISSUE TITLE
Suggestion: "Vor- und zurückspulen" with shorter time periods

### ISSUE THREAD

**Issue by Marc2112** [PaulWoitaschek/MaterialAudiobookPlayer#451]
"Vor- und zurückspulen" has now a lower limit of 10 seconds. I suggest to enable settings down to 1 second.

Reason: For Audiobooks 10 seconds might be ok. But some of us also use the player to learn languages. For some languages it can be very helpful to listen to very short snippets over and over again to get the right tone (especially for tonal languages like Chinese).

**Comment by PaulWoitaschek** [comment]
I increased it to 3s. Hope thats fine for you.
