### ISSUE TITLE
Return after listening a bookmark ?

### ISSUE THREAD

**Issue by erta29** [PaulWoitaschek/MaterialAudiobookPlayer#454]
Hello, 
How to get back to where we had stopped playing after listening to a bookmark ?
Thanks. Best regards.

**Comment by PaulWoitaschek** [comment]
Listening to a bookmark? What do you mean by that? You just click on a bookmark to get to that position.

**Comment by unicorn622** [comment]
After clicking on a bookmark you get to that position, but can't go back to the position where you were listening before. 
E.g. bookmark is at 00:15:00 and you are listening at 00:20:00. So if you click on the bookmark, you will jump to 00:15:00 but it (at least i think) is not possible to go back to 00:20:00

**Comment by PaulWoitaschek** [comment]
Then create a bookmark before you click on another bookmark

**Comment by erta29** [comment]
unicorn622  : it is exactly the problem...

**Comment by erta29** [comment]
unicorn622 : it is exactly the problem I wanted to solve...
