### ISSUE TITLE
Suggestion: Respond to earphone button clicks

### ISSUE THREAD

**Issue by lonchat** [PaulWoitaschek/MaterialAudiobookPlayer#456]
Hi. I currently use Mort Audiobook Player for listening to podcasts and find I use the earphone button to move foreward/backwards [track/folder] and pause/play a lot. I there any chance of integrating this into your player?

Thanks

James

**Comment by PaulWoitaschek** [comment]
You mean your headset control button do not work?

**Comment by aperomsik** [comment]
Headset button stops and starts, but in Mort and Listen you can configure double-clicks and triple-clicks of the headset button for things like short jump back. Here is a screenshot from Listen's headset button settings.
 
![screenshot_20170101-194107](https://cloud.githubusercontent.com/assets/500320/21583705/a73da3fa-d05a-11e6-9f2e-34ff99ec6e54.png)

**Comment by lonchat** [comment]
@PaulWoitaschek, yes, like @aperomsik has just posted. In Mort the button on the earphone can be used to navigate through the tracks/folders.

Sorry it has taken a wile to respond. Happy New Year.

**Comment by nioncode** [comment]
On my headset, pausing, seeking (back + forward 20s) and volume control work just fine.
Do you only have a single button headset control?

**Comment by aperomsik** [comment]
Bluetooth headset buttons including car stereo Bluetooth works great. This
is about single button wired headsets.

**Comment by bagarwa** [comment]
Yep, my headphones have a single button. So, single press, double press and triple press - all having their own actions would be great.

**Comment by PaulWoitaschek** [comment]
I find this to be too specific to put it an action. However you might be able to use an app like this to map the events:

https://play.google.com/store/apps/details?id=com.kober.headset&hl=de
