### ISSUE TITLE
Issue : Automatically starts playing for Media Play trigger even when not opened

### ISSUE THREAD

**Issue by senkumartup** [PaulWoitaschek/MaterialAudiobookPlayer#457]
Issue : Automatically starts playing for Media Play trigger even when not opened

Steps
- This app is not running
- Trigger media play (Say using MacroDroid)
- This app starts playing

Would like to have is that when app is opened or running in background, then this is fine.
Even when not running - Auto opening and playing is annoying. Please fix

**Comment by aperomsik** [comment]
Some might say that's what the media player is for. I actually have the opposite complaint -- the player used to respond better to launch requests from my car but lately I have to launch it manually.
