### ISSUE TITLE
Suggestion: Add an equalizer

### ISSUE THREAD

**Issue by DEM0N194** [PaulWoitaschek/MaterialAudiobookPlayer#459]

**Comment by PaulWoitaschek** [comment]
#211

**Comment by PaulWoitaschek** [comment]
I implemented an equalizer. Can you test it? You can get access to the beta [here](https://play.google.com/apps/testing/de.ph1b.audiobook)

**Comment by DEM0N194** [comment]
Hey, I'd love to test it, but i couldn't get acces to the file.

**Comment by PaulWoitaschek** [comment]
Hm, weird.

I uploaded a version manually, can you check it?
https://play.google.com/apps/testing/de.ph1b.audiobook

**Comment by DEM0N194** [comment]
So i just downloaded it and the equalizer works like a charm, thank you so much for implementing it :)
