### ISSUE TITLE
Scan should recognize subfolders as different books

### ISSUE THREAD

**Issue by rmorabia** [PaulWoitaschek/MaterialAudiobookPlayer#460]
In my audiobook folder, I keep books of the same series in sub folders. The scan ignores this and only keeps them as one book. 

Another fix for this would be to allow us to add sub-folders to the list of folders. Right now, that is blocked. 

Thanks for this player! I think it has great potential to be the #1 player on the Play Store.

**Comment by supachris28** [comment]
Agree on this one - I use this for listening to preaches in multiple churches and my folder structure is:
-church
--preach series
--+audio files for each preach

**Comment by sandybeachit** [comment]
same as issue #475
