### ISSUE TITLE
Suggestion: Support variable bit rates as well as fixed bit rate files

### ISSUE THREAD

**Issue by kaelsidhe** [PaulWoitaschek/MaterialAudiobookPlayer#461]
If you try play a variable bit rate file Material Player incorrectly computes the length of the file.  This can result in the player losing your place and being unable to skip around in the file.

**Comment by PaulWoitaschek** [comment]
Thats not with all the files thats just with the files of variable bit rates that are defect.(i.e comes from manually concatting #323)
