### ISSUE TITLE
Cover lag

### ISSUE THREAD

**Issue by ghariib** [PaulWoitaschek/MaterialAudiobookPlayer#462]
Android: 6.0.1 (Nexus 6P)
Version: 2.7.2.1 (F-Droid)

I have 19 books in my library. The covers from 3 books are (automatically) extracted from the mp3 and for the rest i've put an jpg in their respectively folder.
When i'm on the main menu, click on a book and go back it gets laggy: it takes nearly 1 second to load the covers from the books (which are shown in the list). 
So when i repeat this step a few times (mostly 3 times is sufficient) the covers of a few books will be missing from the main menu. And when i try to open a book now it force closes.
I've enabled the "Send bug reports" feature from the settings and "force closed" the app a few times.

(I think i have the same problem like the reviewer on the play store:
Schade wegen des Coverhandlings (laggt), nicht im mp3 selbst gespeichert, oder vll direkt Painten, weil es einfach sehr laggt. Sehr blöd: Es stürzt oft ab (angehalten))
With kind regards

**Comment by andrewjmetzger** [comment]
I see that you are using the F-Droid latest release, 2.7.2. There is actually a later version, 2.9.2, available from the [Google Play Store](https://play.google.com/store/apps/details?id=de.ph1b.audiobook) -- using the most recent release may resolve your issue.

Failing that, please ensure your files are set up as follows, if they are not already:

    /<audiobooks folder>/
        <book - author>
            <audio files>
            cover.jpg
        <book 2 - author>
            <audio files>
            cover.jpg
        [...]
