### ISSUE TITLE
Suggestion: Sleep timer should play to the end of a chapter

### ISSUE THREAD

**Issue by micressor** [PaulWoitaschek/MaterialAudiobookPlayer#464]
This is an enhancement for #414: 
- Sleep timer should play to the end of a chapter.
- In proximity to sleep timers defined duration.

I'd like to see this feature. Thanks a lot.

**Comment by philipobenito** [comment]
+1 end of current chapter would even be good enough for me. I don't mind setting again.

**Comment by PaulWoitaschek** [comment]
The sleep menu is full enough

**Comment by micressor** [comment]
For me it is an important feature for an audiobook player.
Is it possible to sponsor this feature?

**Comment by PaulWoitaschek** [comment]
Nope, unbribable 😁

However as this is open source, you could always fork.

**Comment by micressor** [comment]
Yes I understood.
But please let this feature request open, it is still a missing feature. May someone will implement it.

**Comment by PaulWoitaschek** [comment]
The point of this app is to have as many missing features as possible.

**Comment by micressor** [comment]
You are very unfriendly!

**Comment by PaulWoitaschek** [comment]
I really didn't mean to! I just try to keep the scope as focused as possible to provide the best user experience.

**Comment by philipobenito** [comment]
For me, sleep to end of chapter would be a huge improvement.

**Comment by micressor** [comment]
@PaulWoitaschek I believe you - and I do my best, to give you feedback from a user perspective.
