### ISSUE TITLE
Won't remember last position

### ISSUE THREAD

**Issue by Slappyface** [PaulWoitaschek/MaterialAudiobookPlayer#466]
I bought a high quality .flac version  of an audiobook, havent been able to check if the bit rate is fixed or varible since im at work now.
Read other issues that stated that it had to be a fixed bit rate. Soo will try that when i get home, just wanted to report it.

**Comment by PaulWoitaschek** [comment]
If this is still happening please comment and I'll re-open

**Comment by dbolton** [comment]
For a similar report, see https://github.com/PaulWoitaschek/Voice/issues/635
