### ISSUE TITLE
Add ability to map bluetooth control events to other events

### ISSUE THREAD

**Issue by wberrier** [PaulWoitaschek/MaterialAudiobookPlayer#467]
I got this idea from the "Akimbo" audio book player app (which isn't in the app store any longer).

My car steering wheel only has two buttons for bluetooth control: skip back and skip forward.  In listening to audio books, I realize I only use two operations: skip back, and play/pause.

It would be really nice to be able to map skip forward to play/pause.

**Comment by PaulWoitaschek** [comment]
I think thats too much of a confusing edge case for most of the users.
