### ISSUE TITLE
Feature request: audio volume boost

### ISSUE THREAD

**Issue by zelenij** [PaulWoitaschek/MaterialAudiobookPlayer#469]
Hi, I am trying to use the player on a new Samsung Galaxy J5 (2016).  For some reason the volume level via speaker (**not** with headset plugged in) is quite low.  This is true for all other players, so seems to be handset issue.  Smart Audiobook player seems to have a feature for exactly this problem - volume boost.  An additional button which makes playback a bit louder on each press.  Would it be possible to add such feature to Material Player as well?

**Comment by PaulWoitaschek** [comment]
#334
