### ISSUE TITLE
Issue: app crashes randomly while playing

### ISSUE THREAD

**Issue by rubricae** [PaulWoitaschek/MaterialAudiobookPlayer#470]
I've recently had a very irritating issue where the app will sometimes crash during playback, and I'm unable to resume playing, change the seek/time, chapter or currently playing audiobook without first clearing the cache and force closing the app MULTIPLE TIMES. 
I'm running the latest store version on CM12.1 (Android 5.1) for Xiaomi Redmi note 2.
I'm not sure where the issue lies here, considering clearing the cache, force closing the app, and restarting the phone are not an immediate fix and usually must be performed multiple times in order to take effect. And then after a few chapters it crashes again and I must start the process over.
I'd love to continue using this app, but it's barely functioning for me currently and I fear I'll be forced to use an alternative.

**Comment by bananabob** [comment]
I would like to add to this.
I was using the app on Android 6 and it worked fine for a couple of days and the crashed while playing.
I then couldn't get it to even start again without a crash.
I have sent in the reports as requested at time of the crash.
Thanks.

**Comment by PaulWoitaschek** [comment]
If this is still present please comment and I'll reopen the ticket.
