### ISSUE TITLE
Feature request: Hold for slider for sleep timer

### ISSUE THREAD

**Issue by nikalas** [PaulWoitaschek/MaterialAudiobookPlayer#474]
Hi!

This is actually a a feature request found on the play store page.

Is it possible to extend the function of the sleep timer button so that when you hold the button 
down for a little while while it opens a slider for adjusting the timer, so as to not have to go
into the settings and changing the default time?

Like so:
Press button - current behavior
Press and hold, then slide - change the timer for _this_ instance

I actually forked the code in the hope of being able to contribute this as a pull request but quickly realized i don't know Kotlin so I'm leaving it here as a feature request.

**Comment by PaulWoitaschek** [comment]
As of 16.08 you can set the time through a dialog popping up
