### ISSUE TITLE
[Feature request] [Super simple] Rewind instead of change track button on lock screen.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [PaulWoitaschek/MaterialAudiobookPlayer#476]
When I listen to an audiobook, the screen is 99% of time locked. It's often that I want to rewind back 20 seconds or so, because I didn't hear something or I want to hear it again, but to do that currently I have to , type in PIN, unlock screen, open app, tap rewind. Sometimes I have to do this every few minutes or even few times in short period.
Currently there are go back one track, play/stop, go forth one track buttons on lock screen. It's definitely a better idea to have there rewind buttons instead. People change tracks much less often and how fast they do it is not as important.

PS That's the best audiobook player for Android, I tried them all.

**Comment by PaulWoitaschek** [comment]
Which Android Version are you using? The buttons on the lock-screen should rewind / fast forward.

**Comment by gerg5c42g542g2c54g52c** [comment]
I use Kitkat 4.4.4.

**Comment by PaulWoitaschek** [comment]
Can you post a video? I can't imagine how that could happen.

**Comment by gerg5c42g542g2c54g52c** [comment]
Did you change that recently? It works now as I wanted...

**Comment by PaulWoitaschek** [comment]
Its like that for more than 1,5 years now. Please comment if you see this issue again.
