### ISSUE TITLE
SD mount point change after Android update: Bookmarks and progress lost

### ISSUE THREAD

**Issue by friday** [PaulWoitaschek/MaterialAudiobookPlayer#477]
Due to a security update my Xperia z3c (and probably a lot more phones out there). No longer uses generic mount points. My previous mount point /storage/exfat_uuid/ has changed to an actual unique id: /storage/XXXX-XXXX/

The problem is, I had quite a bit of information stored as bookmarks, which is now lost, or at least not showing. Can this data still be reobtained? /Android/data/ph1b.audiobook/ only contains images.

Related info I think: http://androidforums.com/threads/marshmallow-6-0-onturbo-2.1007980/#post-7242364

**Comment by friday** [comment]
Oh, and since this is strictly speaking not a bug or feature request I hope it's still ok that I posted it here.

**Comment by PaulWoitaschek** [comment]
Directly related  to #500
