### ISSUE TITLE
Material Player works great except for Android 6

### ISSUE THREAD

**Issue by gnominal** [PaulWoitaschek/MaterialAudiobookPlayer#479]
Material Player works on Android 4.4 and 5.01, but not for Android 6. Under Android 6 it is not possible to address the sd-card. Supplementary I have 2 'things' in it I would like to delete. This doesn't seem to be possible. Fault or Feature?

Thanks for your attention

Gnominal

**Comment by PaulWoitaschek** [comment]
Directly related to #500 
However sd cards should be detected  now.
