### ISSUE TITLE
Wma not recognized

### ISSUE THREAD

**Issue by ilCosmico** [PaulWoitaschek/MaterialAudiobookPlayer#480]
I choose folder with audiobook in wma format but I cannot see nothing, is that an expected behavior?
(I'm using Android 6.0)

**Comment by PaulWoitaschek** [comment]
Wma is a proprietary audio format by microsoft and not supported by Android.

See https://developer.android.com/guide/appendix/media-formats.html

**Comment by ilCosmico** [comment]
I can listen it with VLC...but ok, understand.

On Aug 21, 2016 20:49, "Paul Woitaschek" <notifications@github.com> wrote:

Wma is a proprietary audio format by microsoft and not supported by Android.

See https://developer.android.com/guide/appendix/media-formats.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/issues/480#issuecomment-241274434>,
or mute the thread

**Comment by PaulWoitaschek** [comment]
Vlc is different. They don't use the Android codecs at all. That's why it's like 30mb large.
