### ISSUE TITLE
Equalizer for Amplification

### ISSUE THREAD

**Issue by mmutoo** [PaulWoitaschek/MaterialAudiobookPlayer#481]
This is a great piece of software and I would love to thank the author/authors first. Also I have a suggestion. It would be great if there was an equalizer and an amplifier so that the sound could be amplified in noisy environments like metro.
P.S. On android 6.0.1, sometimes the controller in notification area just disappears and I have to open the app again to see the interface.

**Comment by PaulWoitaschek** [comment]
#211 #459 #334 #223 #469 #388

**Comment by PaulWoitaschek** [comment]
I implemented an equalizer. Can you test it? You can get access to the beta [here](https://play.google.com/apps/testing/de.ph1b.audiobook)

**Comment by mmutoo** [comment]
I could not access the file!
