### ISSUE TITLE
Feature Request: AAC-File Support

### ISSUE THREAD

**Issue by devaux** [PaulWoitaschek/MaterialAudiobookPlayer#483]
Great player!
Is there planned to support file formats like AAC?

**Comment by PaulWoitaschek** [comment]
I just created a wiki entry to answer your question:

[Why doesn't MAP support xyz Media Format?](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/wiki#why-doesnt-map-support-xyz-media-format)

**Comment by alex73** [comment]
Link is broken. Why doesn't Voice support aac ? :)

**Comment by PaulWoitaschek** [comment]
Aac is supported by voice.

**Comment by alex73** [comment]
Supported in .m4a container, but Voice doesn't show .aac files
