### ISSUE TITLE
Poistion resets to beginning of last file after end of book/folder is reached

### ISSUE THREAD

**Issue by brokkr** [PaulWoitaschek/MaterialAudiobookPlayer#484]
What happens: When the end of the last file in a book is reached, the player stops and the postion is reset to the beginning of the last track.

What I think should happen: When the end of the last file in a book is reached, the player stops and the postion stays at the end of the file.

Steps to reproduce: Start any audiobook playing to the end of the last file and note behaviour.

Cases in which the suggested behaviour would be preferable:
- Large audiobooks where you haven't copied all files over at once. 
- Large collections of audiobooks where you'd like to see at a glance which are completed in list view (progress line reaches all the way to the right) 
- Use of Material Player as a podcast player as well as audiobooks. This is my main issue: podcasts are synched with my server on a daily basis. The resetting means I don't go straight in to the most recent episode but have to skip.

Cases in which current behaviour is preferable:
- ?

Are there any? Why would you want to listen to the last file again? If you were going to reset then surely it would make more sense to go the beginning of the entire book/folder, right?

**Comment by philipobenito** [comment]
+1

I'd love to see it be marked as complete with the ability to filter out of main listing.

**Comment by PaulWoitaschek** [comment]
Please try the latest beta and give me feedback if it works as you expect

https://play.google.com/apps/testing/de.ph1b.audiobook
