### ISSUE TITLE
Unable to see books on SD card - Android M, LG G5, factory ROM

### ISSUE THREAD

**Issue by GeorgeBr13** [PaulWoitaschek/MaterialAudiobookPlayer#485]
Unable to see books on SD card - Android M, LG G5, factory ROM

Shows SD card as source from drop down but lists no sub folders. Can only see Storage: 0 sub folders on device main storage.

**Comment by mrsb33** [comment]
I am having this problem too. Just upgraded phone from Note 3 to Edge 7 Marshmallow. I can select the SD card from the drop down, but the list showing from Storage: 0 does not change and I can't select my Audiobook file location. I use Mediamonkey for music playback and have no problem selecting my music files from the SD Card, so this appears to be a MAP issue? I have uninstalled and reinstalled the app, and granted all allowances requested with no luck. Any help? I'd hate to change players - I love MAP!

**Comment by PaulWoitaschek** [comment]
Part of #500
