### ISSUE TITLE
Feature Request: Series Grouping

### ISSUE THREAD

**Issue by MySecretUsername** [PaulWoitaschek/MaterialAudiobookPlayer#487]
Hello,

Was hoping for the feature of grouping a series within the UI. Eg,
# Folder Tree

/AudioBooks/1984/1984.mp3
/AudioBooks/Dark Matter/Dark Matter.mp3
/AudioBooks/Enders Saga/Enders Game/Enders Game.mp3
/AudioBooks/Enders Saga/Speaker for the Dead/Speaker for the Dead.mp3
# App UI

This to show in the UI as I have structured it in the file tree as
[1984] [Dark Matter] [Enders Saga]

Not the actual books within Enders Saga, but the collection, the top level folder.
Then when I tap open Enders Saga I see
[Enders Game] [Speaker for the Dead]
# Uses

This can be used for both grouping of a series as I would like, and others can use it perhaps for media type (Fun, Learning), genre (Comedy, Romantic, Horror, Sci-Fi), person (His, Hers, Children).

I hope that all makes sense :) 

Thank you, Me.

**Comment by philipobenito** [comment]
+1

**Comment by nioncode** [comment]
Should be closed in favor of #473, which is kind of a duplicate.
