### ISSUE TITLE
Exit application when playback timer expires

### ISSUE THREAD

**Issue by nvx2004** [PaulWoitaschek/MaterialAudiobookPlayer#490]
It would be great if one could set the application to exit when the playback timer expires.

Imagine the following scenario: you go to sleep and decide to listen to some music, a podcast, etc. You therefore set the playback timer to not have to worry about the playback distracting you longer than for the predefined time period. As of the latest version of the application, it stops playback once the timer expires but the player does not exit (i.e., it keeps running rather needlessly). So, if one makes use of some battery-saving mode (e.g. the Stamina mode available on Sony Xperia devices) then the phone can never enter the corresponding deep sleep state because the player's activity prevents it. Please do not ask me why this is the case -- I just now that (i) Stamina notifications stating that MAP prevented the phone from entering deep sleep are shown and (ii) battery drains quicker if I keep MAP open (with playback _not_ active) overnight. If, however, the application exited once the playback timer expired, then the device would be able to enter deep sleep thus conserving the energy/keeping the battery life longer.

Thank you for considering this suggestion.

**Comment by PaulWoitaschek** [comment]
The wakelock should be released when the playback is paused an the phone should be ready for deep sleep.
