### ISSUE TITLE
Player forgets last position after reboot

### ISSUE THREAD

**Issue by hudcap** [PaulWoitaschek/MaterialAudiobookPlayer#492]
Most of the times that the phone is turned off and on, the last position is reset to the beginning of whichever book was playing last. Stopping the app does not have this effect.

I cannot find a pattern as to when it remembers and when it doesn't. I tried restarting with the app open, closed in the background, and stopped, but got both results for each.

Also, I'm not sure if this is related, but when I load the app after a reboot, the audiobook list loads gradually, one at a time, as if some cache was cleared. This does not occur after stopping the app.

Running Material Player version 2.7.2.3 on Android 5.1.1 (Huawei Y538)

Note: This issue is related to issue #387, but does not seem to be the same based on the symptoms.

**Comment by hudcap** [comment]
How is the last position stored?
I could try to debug more if I knew where to look.
I tried, but can't seem to find the code that saves the last position.

**Comment by PaulWoitaschek** [comment]
That happens [here](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/v16.08/audiobook/src/main/java/de/ph1b/audiobook/playback/MediaPlayer.kt#L69)
