### ISSUE TITLE
Feature Request: option to play next file in folder

### ISSUE THREAD

**Issue by ml17950** [PaulWoitaschek/MaterialAudiobookPlayer#493]
Hi

Maybe you can add an option in the settings to play next file in a folder if the end of the file is reached. 
This option can also play the first file of the next folder, if the last one of the first folder is played to the end. 

Why? 
I use this really great app as player for my child. She can navigate / choose by her own with the big cover pictures but can only hear one file after another. 
If I use the single book mode, it plays straight forward but she has problems with this small selection dropdown. 

Best regards

**Comment by PaulWoitaschek** [comment]
I'd like to keep it simple. Can't she click back to be back in the cover overview?

**Comment by thedbexp** [comment]
I too would really like a feature like this. I listen to audiobooks on runs and if I have a 2 hour run, but only 50 minutes left on my next book, I cant set it up to play something after the book ends. I think this is the one missing feature for me. I like the app being simple, but it sucks having to pull my phone out mid long run to switch books. I really just want a session based "play next" feature. Maybe I will see if I can make one
