### ISSUE TITLE
Skip Forward on Lock Screen

### ISSUE THREAD

**Issue by daveroberts** [PaulWoitaschek/MaterialAudiobookPlayer#498]
The lock screen currently has a button to skip backwards and play/pause.  It would be nice if it also included a skip forward button.

**Comment by PaulWoitaschek** [comment]
Implemented 9156a6139cf71fae72d9c3a88b15c44e67191bf7

**Comment by daveroberts** [comment]
Thank you! (!ow, three character commit!)
