### ISSUE TITLE
Feature Request: Volume control

### ISSUE THREAD

**Issue by hudcap** [PaulWoitaschek/MaterialAudiobookPlayer#501]
I have some audiobooks that are difficult to hear while driving, despite the volume being at its max.
A way to raise the volume above "100%" would be really useful.

**Comment by PaulWoitaschek** [comment]
#334

**Comment by cvzi** [comment]
Do you know if it is technically possible to implement a "volume reducer"? My audiobook files are too loud even on the minimal android volume level.

**Comment by PaulWoitaschek** [comment]
That's technically possible, can you open an issue for that @cvzi ?
