### ISSUE TITLE
crash on startup when trying to load certain mp3 files

### ISSUE THREAD

**Issue by tastelikecoke** [PaulWoitaschek/MaterialAudiobookPlayer#502]
I get a crash when I open the app with certain folder (Ted) containing mp3 files on the audiobook folder.  When I remove this folder, the crash doesn't happen.  The app is completely unusable because of this.

Here's a logcat for the crash:

[material_crash_log.txt](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/584893/material_crash_log.txt)

**Comment by daveroberts** [comment]
I too am having this issue.  I sent the crash logs via the Android crash report, but if there is a better way to assist, please let me know.

**Comment by daveroberts** [comment]
Possible workaround: I uninstalled the app and reinstalled and I am no longer having this issue.

**Comment by ovidiub13** [comment]
At first it crashed when I added the files. Then it opened, but wouldn't play those files. Then I moved the files to another location and the app started crashing on every start.

I confirm, Reinstalling the app fixes the crash issue, and the files are now playable.

**Comment by daisywreath** [comment]
I reinstalled yesterday but am having issues with crashing again, unfortunately. It worked for a bit but now it crashes after a second or two of playback.

**Comment by PaulWoitaschek** [comment]
I assume this is fixed. If not please comment and I'll reopen.
