### ISSUE TITLE
Not playing after the update 

### ISSUE THREAD

**Issue by vikkio88** [PaulWoitaschek/MaterialAudiobookPlayer#503]
Hi there, after the last update now the app won't play anything. No errors reported or anything just clicking the button play in any view is not doing anything. There's a way of getting some info that you might need to solve this issue? Is just me?

**Comment by PaulWoitaschek** [comment]
Is this fixed as of the latest release [2.9.1](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v2.9.1) (not fully published yet)

**Comment by vikkio88** [comment]
Hey there, I can't test it because I dropped my nexus 5 into the water the other day, and now is dead :cry: 
thanks for the info, once I will buy a new phone I will test it out asap.

**Comment by PaulWoitaschek** [comment]
Good luck with your phone. Just broke my 5x ;-)
