### ISSUE TITLE
Rectangle display cover art (or option to do so)

### ISSUE THREAD

**Issue by GrantVanderBurg** [PaulWoitaschek/MaterialAudiobookPlayer#505]
All of my audiobooks have book covers as cover art (since they are way easier to find those images online rather than the square album-type cover art). Therefore, it would be great to have book art in the standard vertical, rectangle aspect ratio would be great (not sure what exactly is standard ratio, if there is any). Having the option to change from the square to rectangle would be great as currently the square cover art is stretching the original rectangles.

P.S. Awesome app by the way! It's such a great example of material design.

**Comment by GrantVanderBurg** [comment]
Oh! Forgot to ask as well, any option to add Google Drive folders as a source?

**Comment by PaulWoitaschek** [comment]
#98 #52
