### ISSUE TITLE
Audio dramas not showing

### ISSUE THREAD

**Issue by tbs123456** [PaulWoitaschek/MaterialAudiobookPlayer#508]
It will show some of the audio dramas I have(all in mp3 format) but not all of them. I found that removing the artwork from the mp3 file it will then show. File size of the artwork does not seem to matter as one that is 88k won't display, but one that is 2meg will display. I have the naming convention to be all the same. Example (dwst-bf-101) - the toy or (dwst-bf-102) - museum peace. The museum peace audiobook will show, but the toy wont unless I remove the artwork.

**Comment by tbs123456** [comment]
Should add I have a 32gig Nexus 6 on Android n.

**Comment by tbs123456** [comment]
I figured out that using artwork that is 1417x1417 is to large so material player won't display it. Not sure if it a bug or not.

**Comment by PaulWoitaschek** [comment]
Can you send me one file that doesn't work with the artwork to woitaschek@gmail.com?
