### ISSUE TITLE
Control for scrobbler

### ISSUE THREAD

**Issue by ketan-a** [PaulWoitaschek/MaterialAudiobookPlayer#510]
By default whatever audiobook I'm listening are broadcasted to audio scrobbler. I'm using [sls](https://github.com/tgwizard/sls) for scrobbling my music. Can we have a control for scrobbling?

**Comment by PaulWoitaschek** [comment]
Should be fixed as of 600579f72810e394d4281bfdfd28d8d07a7a9dd6

**Comment by ketan-a** [comment]
Thanks @PaulWoitaschek for the fix 👍

**Comment by PaulWoitaschek** [comment]
Credit goes to @HumbleBeeBumbleBee
