### ISSUE TITLE
Playback speed control forgets after each use

### ISSUE THREAD

**Issue by artnking** [PaulWoitaschek/MaterialAudiobookPlayer#513]
Since the most recent upgrade, when I open the app and restart an audiobook, it defaults back to play at 1.0 speed.  It no longer remembers the playback speed from the previous session with the same book.

**Comment by KBalderson** [comment]
I have a similar issue. I will add that, while the playback speed is slowed to 1.0, the slider still showed my speed at the number to which I had i previously set.

**Comment by Steviex2Shoes** [comment]
I was coming here to say the exact same thing or at least see if others were having this issue.  I listen at playback around 1.4 and have noticed it the book reads at 1.0 the slider says 1.4 and as soon as you go to the playback speed section it speeds up to what you have selected.

**Comment by PaulWoitaschek** [comment]
Should be fixed as of 0d42321284473d447e00a4535e606ea0906a1942
