### ISSUE TITLE
Does Material Player support ReplayGain?

### ISSUE THREAD

**Issue by etnoy** [PaulWoitaschek/MaterialAudiobookPlayer#514]
I often listen to audio books while driving, but cars are noisy and sometimes the audio books are recorded with a low volume. To combat this, I will start performing replaygain on my tracks. I prefer to do this losslessly, i.e. with the replaygain file tags only.

This begs the question, does Material Player use ReplayGain tags to control the volume? Otherwise, I'll have to alter the tracks permanently to get the correct gain.

Thanks

**Comment by PaulWoitaschek** [comment]
#223
