### ISSUE TITLE
Support for Android Auto

### ISSUE THREAD

**Issue by tilden** [PaulWoitaschek/MaterialAudiobookPlayer#515]
Material Player currently doesn't support Android Auto, but if it did, it would be really convenient if it could be used when running Auto.

Luckily, it appears to be (relatively) straightforward for audio apps (https://developer.android.com/training/auto/audio/index.html).
I'd be interested in implementing this feature myself. Would a PR theoretically be welcomed?

**Comment by tilden** [comment]
Just realized this was a duplicate of #231, sorry about that.

**Comment by PaulWoitaschek** [comment]
A PR is welcome, see the linked ticket. Currently I have very little time but support is theoretically there already.
