### ISSUE TITLE
Volume adjust on per book basis

### ISSUE THREAD

**Issue by ryanwalexander** [PaulWoitaschek/MaterialAudiobookPlayer#516]
I'd really appreciate it since the levels of some of my recordings are far lower than my GPS app or other notifications when I'm driving.

**Comment by Musiphilos** [comment]
+1

**Comment by sandybeachit** [comment]
So you mean to have a separate volume setting for MaterialAudiobookPlayer and not a seperate volume option for each and every book ?

**Comment by ryanwalexander** [comment]
Hi Paul,

I love your app. Thank you for making it.

I mean a gain adjustment that you can set per audiobook. So basically a
separate volume adjustment for each and every book but it must allow louder
playback than the normal maximum.

The problem I want to solve is that some audiobooks are recorded at a much
lower volume level than the rest of Android notifications. So directions on
navigation are sometimes REALLY loud when I have to increase the volume to
hear a book.

Thank you,
Ryan

**Comment by ryanwalexander** [comment]
I was thinking more about it and a simple gain level for the whole app (not
separate by book) would also be book because usually we listen to one book
at a time.

What do you think?

**Comment by PaulWoitaschek** [comment]
Implemented :)
