### ISSUE TITLE
Feature request: Voice commands

### ISSUE THREAD

**Issue by ryanwalexander** [PaulWoitaschek/MaterialAudiobookPlayer#517]
I always start Spotify with "listen to xx on Spotify" and material player with "open material player". 

Would be sweet if I could just say "listen to material player" or something similar and it resumes the book I've been listening to.

**Comment by ryanwalexander** [comment]
Excellent app by the way, thanks for keeping it simple.

**Comment by PaulWoitaschek** [comment]
Comes hand in hand with #231
