### ISSUE TITLE
Feature Request: Choosing where the name of the audiobook come from

### ISSUE THREAD

**Issue by thelele** [PaulWoitaschek/MaterialAudiobookPlayer#518]
I have about 50 audiobooks. Each audiobook is inside a folder name the following "Author name - Title of the audiobook". I don't change the name of the actual mp3 file because sometime I have one per chapter.

Unfortunaly the material player use sometime the file name, or the mp3 tag of the file as the title of the audiobook. Which lead to some weird and not clean title like "my audiobook Disc 1". 

It would be nice to have an option or something that allow us to automatically have the audiobook folder's name as the audiobook title.

Thanks for your hard work and awesome player :)

**Comment by PaulWoitaschek** [comment]
#377

**Comment by thelele** [comment]
t

**Comment by PaulWoitaschek** [comment]
Yes, thats the fallback option. Else you can still rename the books manually.

**Comment by thelele** [comment]
Yes but doing it for more than 50 books, especially when you already did it with the folder's name on Windows, it's tiring.

**Comment by thelele** [comment]
Hi,

after not using Material Audiobook Player for a while, and after changing SD card + uninstall and install again the app. Now it looks like that the player use the first mp3 name as the name of the audiobook. 

So my work around by deleting all mp3 tags to force the app to use the folder's name as the name of the audiobook don't work anymore.

Have you change the way the app pick the name ?
Is it possible to get the older apk of the app before this change ? Because I really care about the name of the audiobooks and I can't rename one by one on the app, it would be way too long.

Thank you
