### ISSUE TITLE
Problem with automatic bookmarks

### ISSUE THREAD

**Issue by rl1234567890** [PaulWoitaschek/MaterialAudiobookPlayer#519]
I have several podcasts in separated directories. If I listen to a work, stop, and try to restart a second work I get the following error: 

_Unfortunately, AudioFX has stopped._

and I lose the automatic bookmark in the second work.

Of course, I'm still grateful for your application.

**Comment by PaulWoitaschek** [comment]
Its most probably related to your equalizer. What happens if you disable it?

**Comment by rl1234567890** [comment]
It seems it cannot be disabled. I have a Nexus 5, running the latest release of  Cyanogenmod.

**Comment by PaulWoitaschek** [comment]
Go to the app info of Audio-FX and disable it.

I still don't get how this is related to bookmarks. You can set a bookmark when enabling the sleep timer. You mean your created bookmark is lost? Can you describe what exactly you do and what you expect?

**Comment by rl1234567890** [comment]
It cannot be disabled. The button is gray.

**Comment by PaulWoitaschek** [comment]
It's hard to say what happened here. Does MAP also stop? What exactly happens after your AudioFX stopped? Is this the same with all files?

**Comment by rl1234567890** [comment]
No, MAP would not stop but simply proceed to the next mp3 in the directory. However, it seems that with the new version of MAP, although AudioFX stops, your program doesn't lose the last position in the file any more. It does happen with all files, when I switch from one book (or podcast) to another.

**Comment by PaulWoitaschek** [comment]
Great!

I found information on disabling the AudioFx [here](https://www.reddit.com/r/cyanogenmod/comments/4grj2w/how_to_disable_audio_fx/), maybe it helps you.
