### ISSUE TITLE
Dont work fine for .aac and .wma

### ISSUE THREAD

**Issue by itrolaznog** [PaulWoitaschek/MaterialAudiobookPlayer#520]
Hello. I'm just beginning to try your application, that seems great, thanks.
The first thing I realized is that, when reading .mp3 files, everything is OK. But it seems not be working fine with two kinds of files:
- .ACC: The audio is read but, when pausing it, it restart from begining, and the duration bar to find another starting point doesn't work.
- .WMA: It's not recognized. It says that the file is corrupted. I can read it with other players.
Regards

**Comment by PaulWoitaschek** [comment]
The AAC files are most probably corrupted. See #347 
Wma is not supported by android #480 #143
