### ISSUE TITLE
[Feature Request] Option to add 2 more FF/RWD buttons with custom times

### ISSUE THREAD

**Issue by Cormak** [PaulWoitaschek/MaterialAudiobookPlayer#525]
Currently we only have 1 Fast Forward button and 1 Rewind button and they both have the same custom time shared between them. 

Can we have an option in the settings page to add another fast forward button and another rewind button with unique custom time options so we can have something like:

<< 60 seconds  < 30 seconds  - PLAY - 30 seconds > 60 seconds >>

This would be useful for any particular style of moving back and forth through audio.

**Comment by PaulWoitaschek** [comment]
I like to keep the structure simple. Thanks for you suggestion.
