### ISSUE TITLE
Update on F-droid

### ISSUE THREAD

**Issue by forteller** [PaulWoitaschek/MaterialAudiobookPlayer#526]
Material has not been updated i F-droid for quite some time now: https://f-droid.org/repository/browse/?fdfilter=material&fdid=de.ph1b.audiobook

I'd appreciate it a lot if you'd update it to the latest version. I don't use Google Play. Thanks!

**Comment by PaulWoitaschek** [comment]
It's not me who's updating it, it's them. I offered my help but they seemed not interested. Maybe if you open a ticket there they try again.

**Comment by forteller** [comment]
Hi. I [asked them about this](https://gitlab.com/fdroid/fdroiddata/issues/570).

This is the reply I got:

> See https://f-droid.org/wiki/page/de.ph1b.audiobook. As far as I know, noone has figured out how to install that from the android SDK properly.

Going to that page I find:

> 2.9.2
>
> We can't build this version: The build for this version appears to have failed. Check the [build log](https://f-droid.org/wiki/page/de.ph1b.audiobook/lastbuild_146).
>
> Version code: 146 

So, maybe, looking at that log, there is something you can do to help them build it?

Thanks!

**Comment by PaulWoitaschek** [comment]
It just says it can't find the latest tag they check out. Maybe they didn't pull it right?

**Comment by forteller** [comment]
But they've [tried and failed](https://f-droid.org/wiki/page/de.ph1b.audiobook) to build all the latest versions since 2.7.2.3? Maybe if you reply to the issue I opened over at F-droid you might be able to figure this out together?

I wish I could help more, but I'm no coder and don't actually know anything that might help.

Merry christmas, and thanks for all your great work! :)

**Comment by PaulWoitaschek** [comment]
As boris pointed out they cannot build it with ConstraintLayout.
Until that issue is fixed I always try to upload an apk of the latest release in the release tab:
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases

**Comment by bitinerant** [comment]
I would really like to see this app on F-Droid again.  I appreciate it being open-source, but I feel being on F-Droid adds additional credibility, not to mention convenience for those of us who don't have Google Play on their devices.

**Comment by PaulWoitaschek** [comment]
That's not up to us currently. They don't build any project right now.

**Comment by bitinerant** [comment]
I don't understand.  This page shows 14 built just in the last week:  https://forum.f-droid.org/

**Comment by bitinerant** [comment]
I don't understand.  Many apps have been built recently, e.g. [Conversations](https://f-droid.org/repository/browse/?fdid=eu.siacs.conversations) and [Gadgetbridge](https://f-droid.org/repository/browse/?fdid=nodomain.freeyourgadget.gadgetbridge).

**Comment by PaulWoitaschek** [comment]
They use an old version of gradle. Fdroid has issues with gradle 3.5.
See https://gitlab.com/fdroid/fdroiddata/issues/693

**Comment by bitinerant** [comment]
It's back on F-Droid!  Version 3.2.0.3 appeared there a couple of days ago.  :-)  Thank you, Paul and others for your work on this.
