### ISSUE TITLE
Material skips last 1 or 2 seconds of each file

### ISSUE THREAD

**Issue by derpeter** [PaulWoitaschek/MaterialAudiobookPlayer#53]
Hi,

on my nexus5 Material player skipps the last 1 or 2 seconds of each file. This is now the second audio book where that happens. If i push the back button after that happens i get back to the last file and can here the skipped part. I'm using version 1.2.5.1 from f-droid. The books are all mp3s.

**Comment by lightonflux** [comment]
If it still interest you i can send you a file which triggers the bug. But is is flac so it is around 30MB. Can i send it via email to the account listed in Google Play?

**Comment by Ph1b** [comment]
That would be helpful. Maybe upload it to a hoster and send a link because of limited file sizes on email attachments.

**Comment by ChrisChros** [comment]
Hello, yes please, try to send it via mail, will see if it passes trough.

Am 13.01.2015 um 14:41 schrieb lightonflux:

**Comment by em-a-il13** [comment]
Is there anything new about this bug?
This problem is really annoying for me.
If you need an audio-file which causes the problem I can send you one.

**Comment by Ph1b** [comment]
Please do so (woitaschek@gmail.com)

**Comment by Dain42** [comment]
I'm also seeing this issue on multiple devices when playing .ogg encoded files. It's present on all .ogg files, but I am not seeing the same issue with .m4a (aac) files or .flac files.

I've tested this on multiple devices and multiple versions of Android.  If a few more test files would be helpful I can provide them, as well. If you need anything from my end, I'd be happy to try to troubleshoot as needed.

**Comment by j-opificius** [comment]
Seems worse when playing through Bluetooth. It's as if reader moves on to next file when EOF has been read but before last audio chunk of previous file has finished streaming out.

**Comment by Ph1b** [comment]
Still happening with [latest nightly](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-2015-11-28)?

**Comment by PaulWoitaschek** [comment]
[This](https://github.com/AntennaPod/AntennaPod/issues/837#issuecomment-173871217) is a solution.

**Comment by zerodogg** [comment]
I have a similar issue, though I'm uncertain if it is the same. Material Player is skipping the first 1-2 seconds of a file. Ie. «Chapter 11» ends up being «11».  It started occurring some time during the past few (3-4) months.
