### ISSUE TITLE
Vorbis and opus codecs are supported, but not the containers

### ISSUE THREAD

**Issue by wessven** [PaulWoitaschek/MaterialAudiobookPlayer#530]
I have done some experimentation and found that Material Audiobook Player supports both the [Vorbis](http://www.vorbis.com/) and [Opus](http://opus-codec.org/) codecs, but only if they are encapsulated in MKA/MKV files.  The Opus (.opus) and [Ogg](https://www.xiph.org/ogg/) (.ogg / .oga) _containers_ are not supported.  This means that it is now necessary to wrap a podcast or audiobook, which is for example encoded in the more efficient Opus format, in an MKV container, and in the process the metadata is lost.

Can support for these open-format containers please be added?

**Comment by PaulWoitaschek** [comment]
If the opus codec is supported from android 5 and above.

If something can be done with the container handling this could be done upstream at [exoplayer](https://github.com/google/ExoPlayer)
