### ISSUE TITLE
[Bug] Unable to change playback tempo

### ISSUE THREAD

**Issue by moriakaice** [PaulWoitaschek/MaterialAudiobookPlayer#531]
On Moto G4 running on Android 6 I am able to change the speed/tempo of the playback - it's done by the third icon inside audiobook.

On Moto E running on Android 4.4.4, however, there is no such icon and therefore the option is not available.

Is that due to some icon missing in the system that you are using? Can the feature be implemented with a text option in menu?

**Comment by PaulWoitaschek** [comment]
See #507 

> Sorry for that. The custom speed was very instable and led to many crashes. So after much thinking I decided to offer a stable version and leave out a feature.

>As of now the custom speed is only available on Marshmallow and greater.
