### ISSUE TITLE
Corrupt file on track change

### ISSUE THREAD

**Issue by weshaw** [PaulWoitaschek/MaterialAudiobookPlayer#533]
Just updated to 2.9.3.1. Now when changing to the next track the player says the the file may be corrupt. Closing and reopening the app lets you continue playing.

**Comment by PaulWoitaschek** [comment]
Is this the case with all books?

**Comment by weshaw** [comment]
It is happening to this book only, but it is the only book that has
this file format m4b I have. mp3's seem to work fine. It was not
happening before the update, and started immediately after. These
files seem to have some meta errors though as the time signature on
each file is 45 minutes and as far as I can tell the files themselves
are shorter. The app will keep playing past the end and I will have to
skip to the next track. This was the case before the update too, the
only change is the app now see's the  next track as being corrupt and
will not play it until reboot. I will re-encode the files this should
fix the problem, I will let you know if it does not.

On 1/10/17, Paul Woitaschek <notifications@github.com> wrote:
> Is this the case with all books?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/issues/533#issuecomment-271780807


-- 
Weston Shaw
  Web Scripting Engineer
  www.avallo.com
  weston@avallo.com
  weshaw@gmail.com

**Comment by PaulWoitaschek** [comment]
Can you send me such a file to the mail in my GitHub profile?
