### ISSUE TITLE
Feature request: option to recreate sleep timer automatically

### ISSUE THREAD

**Issue by 1mi** [PaulWoitaschek/MaterialAudiobookPlayer#535]
Hello,
as the title says, a separate option for automatically recreating the sleep timer would be great.
I would like to set the sleep timer only once and forget about it. I don't want to press the play button AND the sleep timer button every time.

The reason for this is that I would like to avoid to remember that I have to press the sleep timer too when listening to audio books at night. Just forget once and you can wonder in the morning why your alarm clock didn't sound, why is your phone discharged and so on...
When you are fresh, you can remember it more easily to press both buttons, but once the sleep timer expired and I would like to listen some more I will have to unlock my phone half asleep, press play AND the last thing i want to remember is to press the sleep timer too in order to avoid such catastrophe.

How hard is this to implement? I think it would be a nice addition to this already great player that would differentiate it from the competition.
Thanks

**Comment by PaulWoitaschek** [comment]
It's not hard to implement.

But I think this request is too specific that everyone should have it.

**Comment by 1mi** [comment]
Hi Paul, 
this would be very important to those that want to use the sleep timer for sleeping, which I think is one of the main use cases for a player with a sleep timer. As it was when I wrote this it would rather keep you awake.

Anyway I experimented recently with the "shake to reset" feature and I find it very close to what I want, because it starts playing AND it recreates the sleep timer all at once. However it doesn't work with the screen off and I have to shake it quite hard to work. It would look weird if you start to shake your phone in the middle of the night now and then...

Could the "shake" feature be modified to work with just pressing the button to turn the screen on (or any other hardware button will do it)?
This could be in addition to shaking or as a default option when the screen is off and would work for a certain duration after the sleep timer expired, for example for a fixed number of minutes after playing has stopped, or for a period equal to the sleep timer.
Would you please reconsider this?
