### ISSUE TITLE
[question] When was playback speed removed ?

### ISSUE THREAD

**Issue by mattjmattj** [PaulWoitaschek/MaterialAudiobookPlayer#536]
Hi,

I noticed that playback speed was removed from MAP in lower Android versions. Read a couple of issues about that and I understand that you might arguably have good reasons for removing this feature. For me, playback speed was the main feature of this player and I will stop using MAP if I don't get the playback speed back.

So my question is : what version should I downgrade my MAP in order to get the playback speed adjustment back ?

Personal opinion : marking the feature as possibly unstable would have been enough. It worked for many of us and it's a shame that you removed it for all

**Comment by PaulWoitaschek** [comment]
The last version with the old player is 2.8.x. I'll upload the latest 2.8.x apk when I'm back home in the evening.

It was not disabled for all but only for people with Lollipop and below. The majority of users has that feature. 

The new player has some advantages we can't get with the old player, like the just implemented gapless playback or codec extendability. And stability ofc.

But as their API is completely different so it's not possible to maintain both players at the same time and just mark the playback speed as unstable.

**Comment by mattjmattj** [comment]
According to https://developer.android.com/about/dashboards/index.html , Android M+ users represent only 30% of Android users. Thank you anyway.

**Comment by PaulWoitaschek** [comment]
That's not or user base. Ours is 80 % male, tech affine and about 55% on Marshmallow and nougat.

**Comment by PaulWoitaschek** [comment]
I uploaded the last 2.8.x apk at the [Release Page](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v2.8.0.4.3)

**Comment by pminhn** [comment]
It took me a few days of frustration before I finally find this page. I am very surprised to see you removed the playback speed feature for users on Lollipop and below deliberately. You mentioned the users are "55% on Marshmallow and nougat". Why would you alienate the remaining 45% of the user base? Playback speed is one of the most important feature for an audiobook player. Without it, the remaining 45% will have to find another player, and you will lose almost half of your users. Would it be better to release the older version for users on lower versions of Android as another app (e.g. Material Player Classic)?
(Anyway, thank you for a job well done, and thank you for releasing the source code as open source)

**Comment by PaulWoitaschek** [comment]
It's back!
