### ISSUE TITLE
Wrong length in player when listing to large MP3 files.

### ISSUE THREAD

**Issue by SirBisgaard** [PaulWoitaschek/MaterialAudiobookPlayer#537]
I am listing to large MP3 audio book files, where the book is one file.

The one you can see below is 121 MB. The length of the book is 02:07:13.
This error happens to many of my audio books, that is around that ball park..

I think the problem is the media analyser after looking at your code.
[MaterialAudiobookPlayer/audiobook/src/main/java/de/ph1b/audiobook/features/BookAdder.kt: 289 ](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/9b35db4ed61551779a185937e070d822e4de2f77/audiobook/src/main/java/de/ph1b/audiobook/features/BookAdder.kt)

![bug](https://cloud.githubusercontent.com/assets/18302592/21943221/93439cb8-d9d0-11e6-918a-70417a7c0d73.png)

**Comment by PaulWoitaschek** [comment]
The problem is most likely in your files. Please try if the fix suggested in #443 works for you.
