### ISSUE TITLE
Feature request: Refresh menu option

### ISSUE THREAD

**Issue by VDK** [PaulWoitaschek/MaterialAudiobookPlayer#539]
Newly added audiobooks don't get listed automatically on launch. Adding them individually gives you an error when the audiobook is in your audiobook folder  but does trigger a refresh. This is a bit cumbersome.

**Comment by PaulWoitaschek** [comment]
They do get added, it just takes some time.

**Comment by VDK** [comment]
telling users to wait is not really user friendly 😠

**Comment by PaulWoitaschek** [comment]
I don't get it. What's not user friendly?

**Comment by VDK** [comment]
Having to wait for the app to update after you've added a new folder to your folder of audiobooks instead of being able to hit a refresh button.

**Comment by PaulWoitaschek** [comment]
When you add a folder it interrupts the current scan and starts a new one.
When you enter the main screen it starts a new scan each time but without interrupting the current scan.

So it is refreshing itself. With giving the option to manually refresh, it would just take more time.
