### ISSUE TITLE
Cursor doesn't remember position in file

### ISSUE THREAD

**Issue by eqw3rty** [PaulWoitaschek/MaterialAudiobookPlayer#543]
Player can not remember position for large *.mp3 files (e.g. 500mb). Can be that audio files are concatenated with wrong metadata. But I can not reproduce this issue on my computer or in another audiobook player on my phone.
PS: mp3val doesn't help in this case

**Comment by yamaha252** [comment]
I have the same issue for some audiobooks. The files of its isn't large (5-7mb), but the player doesn't save cursor position.
For example: magnet:?xt=urn:btih:34cc38efafa5c92d359089055f7dd1d203306ca2&dn=%D0%9C%D0%B0%D1%82%D0%B5%D1%81%D0%BE%D0%BD%20%D0%A0%D0%B8%D1%87%D0%B0%D1%80%D0%B4%20-%20%D0%9A%D1%83%D0%B4%D0%B0%20%D0%BF%D1%80%D0%B8%D0%B2%D0%BE%D0%B4%D1%8F%D1%82%20%D0%BC%D0%B5%D1%87%D1%82%D1%8B%20%28%D0%9A%D0%B8%D1%80%D1%81%D0%B0%D0%BD%D0%BE%D0%B2%20%D0%A1.%29&tr=http%3A%2F%2Fbook-tracker.org%2Fannounce.php%3Fpasskey%3Db1554219a5c6fa18e0e1e230b1ada9137a390629&tr=http%3A%2F%2Ftracker.tfile.me%2Fannounce.php%3Fak%3D11543428e0%26&tr=http%3A%2F%2Fi.bandito.org%2Fannounce.php%3Fak%3D11543428e0%26&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fi.bandito.org%3A80%2F

**Comment by caccabomber** [comment]
same things happen for me on mp3 around 1h30minutes. It keeps the position if i close the app and reopen it, but not after a phone reboot

**Comment by eqw3rty** [comment]
@caccabomber It works differently for me. First, player keeps displaying wrong length of audio file, e.g 1m30s. But the actual length of this file is more than 30 minutes. Second, cursor is able to play audio after 1m30s. But if you press pause and play again, it will start from 1m30s.
@PaulWoitaschek Any thoughts about this issue? I can provide audio samples.

**Comment by PaulWoitaschek** [comment]
@eqw3rty Yes, thats usually the case with defect media. For example if you just concat many files without adjusting the headers. For mp3 usually something like http://home.gna.org/vbrfix/ works

Or if you are using ffmpeg:
```
ffmpeg -i brokenFile.mp3 -acodec copy brokenFileFixed.mp3
```

That will keep the audio part and not re-compress it while reparing the headers.

**Comment by eqw3rty** [comment]
@PaulWoitaschek In that case issue can be closed. Thanks!
