### ISSUE TITLE
Support for several books from one author (in subfolders)

### ISSUE THREAD

**Issue by github-user-1** [PaulWoitaschek/MaterialAudiobookPlayer#545]
I have my audiobooks organized in the following way (folders):

`/audiobooks/<author-1>/<audiobook-1>`
`-------------------- /<audiobook-2>`
`-----------/<author-2>/<audiobook-x>`
`...`

This unfortunately results in the books from one author to be listed as one book which effectively makes it unusable - so e.g. from `<author-1>` the audiofiles from folder `<audiobook-1>` and `<audiobook-2>` are mixed up appearing as one book.

If this could be changed that in the end one folder/subfolder is handled as one audiobook that would be just great and what a typical end-user might expect to happen.

Apart from this issue the app is really great and one of my absolute favorites!

**Comment by imuli** [comment]
If you add the author folder as a "Folder with multiple books" it should do what you're after. That does have the unfortunate sideeffect of needing to add all the authors individually.

I'd love to see an "every directory is playable" feature. When you browse to a directory with subdirectories you could either play the whole thing or choose a section to play, and it would keep track of your position in all of them (series, seies/first_book, series/second_book) seperately. This seems like it would work with your organizational structure better than the current scheme.

**Comment by PaulWoitaschek** [comment]
#473
