### ISSUE TITLE
Defect File after deleting folder

### ISSUE THREAD

**Issue by caccabomber** [PaulWoitaschek/MaterialAudiobookPlayer#546]
I finished listening to an audiobook, and erased its folder. Now the app is always popping up and giving me "Defect file, the following file may be corrupt".
The error remains even after a reboot. Even after i close the app and disable notification for Material player app in settings, it appears when i'm using other apps.
Android 5.1

**Comment by pdc1** [comment]
I have been seeing this too and it's very annoying. Last night it happened roughly once per minute! Very annoying when trying to read an ebook.

Just to be perfectly clear, the file is not corrupt, it's not even there! The fix should be simple, check for existence before trying to play.

Before deleting the directory, I made sure to stop playback and navigate to the top level directory before using a different app to delete the directory. However, Material Audiobook Player REALLY wants to keep playing the last file....

**Comment by PaulWoitaschek** [comment]
Thanks for you reports.

Can you check if [2.9.3.5](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v2.9.3.5) fixes your problem? It's also available in the [beta](https://play.google.com/apps/testing/de.ph1b.audiobook).

**Comment by pdc1** [comment]
Hi Paul, unfortunately I do not see any difference after installing the beta. I opened and closed it a few times and each time I close it, it pops back up with Defect file. I verified google play installed the version you listed.

Let me know if there's anything else you'd like me to try.

**Comment by PaulWoitaschek** [comment]
Thanks for testing.

The actual issue wasn't the behavoir itself (I'm fine with a single error message after the user deleted some files). The acutal issue was with the persistent storage not being updated correctly. This should be fixed as of 637478741e8f64f6293d8108805d9db1340f7ccd
Please report if it doesn't; I just uploaded a new beta.

**Comment by pdc1** [comment]
I had to uninstall the app yesterday due to the issue happening so often. However, I installed the latest beta and cannot reproduce the problem, so I think that has fixed it. Thanks!
