### ISSUE TITLE
'Add Timer' icon doesn't position correctly on Samsung 8" tablet

### ISSUE THREAD

**Issue by MartinCorteza** [PaulWoitaschek/MaterialAudiobookPlayer#550]
With the recent version, the 'add timer' icon (the red circle with white plus sign) disappears at about one  third of its height behind the numeric keyboard for entering the sleep time. Orientation of the tablet doesn't change this positioning problem.

**Comment by PaulWoitaschek** [comment]
What do yoy refer to as the recent version? In the latest version that should be fixed.

**Comment by MartinCorteza** [comment]
You're right, I got the update today, position is fixed. Thanks :)

**Comment by PaulWoitaschek** [comment]
Great :)
