### ISSUE TITLE
Seeking impossible in (large) webm files

### ISSUE THREAD

**Issue by derSeddy** [PaulWoitaschek/MaterialAudiobookPlayer#551]
With the help of the XDA app Y Music I downloaded the audio of some YouTube videos in webm format. 
They play fine in Material Player but the player is unable to seek in the files and thus is unable to remember the playback position. The files are quite long, close to an hour, but I don't know if this matters. 
In Androids dmesg log I get an error of MatroskaExtractor: Did not locate the video track for seeking. This might be related to the problem.

**Comment by derSeddy** [comment]
I did a bit of digging and sadly found that solving this would be a very hard task. I asume this app uses the default Android media engine, which uses libstagefright. And hardwired inside this library there is the code that causes this problem, along with the comment "Always *search* based on the video track, but finalize based on mTrackNum". So seeking in webm without a video track is simply not supported. There are two ways to solve this: Either use a different media library or contact Google and make them solve the problem. Both seem a bit unrealistic to me. I will start downloading the files in mp3 format now.

**Comment by PaulWoitaschek** [comment]
Wow a technical bug report  +1: 
Yeah, audio is sometimes a pain on android
