### ISSUE TITLE
FLAC files are not detected

### ISSUE THREAD

**Issue by floriangosse** [PaulWoitaschek/MaterialAudiobookPlayer#552]
I have a audiobook out of FLAC files but the audiobook is not detected.

I use a audiobook folder for multiple audiobooka but I tried it also with a specific audiobook folder. It also didn't work.

**Comment by PaulWoitaschek** [comment]
Which version of MAP are you using? Which Android version are you using?

**Comment by floriangosse** [comment]
I'm using Material Audiobook Player 3.0.7 on Android 7.1.1
-- 
Florian Goße
flo@essog.de

**Comment by PaulWoitaschek** [comment]
What is the file ending? Do all files not get detected? How is your folder setup?

**Comment by floriangosse** [comment]
As default I use multi audiobook folder, but I tried it with a single audiobook folder too, but didn't work.

All files have the file extension `flac`.

**Comment by floriangosse** [comment]
Do you need more informations to reproduce it? I want to help. :)

**Comment by PaulWoitaschek** [comment]
Can you send my l me such a file to woitaschek@gmail.com?

**Comment by PaulWoitaschek** [comment]
Should be fixed as you 3.3
