### ISSUE TITLE
option for manual file rescan

### ISSUE THREAD

**Issue by FolkyHobbit** [PaulWoitaschek/MaterialAudiobookPlayer#555]
related to 299 but with other motivation. If a audiobook is added to the audiobook folder it takes a while to show up in the app. I would like to be able to start listening immediately and not wait for some minutes. Therefore I would love to have a way to trigger a immediate file rescan.  

I would suggest a pull-down gesture in the audiobook list to trigger this action since this is a common way that other material apps trigger a refresh (for example the gmail app).

**Comment by PaulWoitaschek** [comment]
A manual file scan does not fit in how the player works. However I just introduced a change that massively increase the scanning time.

I added a timestamp to each chapter that contains the time of the last modification of the file. When the file to scan has the same timestamp, that chapter will be used and the metadata won't be scanned at all.
For my music collection (about 16 gigs) it decreased the scanning time from 1m:30s to about 0.5 seconds.

The first scan will however take its time, but there is no way around that.

Can you test the version and tell me if it works as expected?

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v3.0.13-RC

**Comment by PaulWoitaschek** [comment]
You can also grab the latest version by joining the beta:
https://play.google.com/apps/testing/de.ph1b.audiobook

**Comment by FolkyHobbit** [comment]
The time between saving the book to my phone and it showing up indeed was dramatically reduced it seems in the beta, thank you for that work! Only thing that bid me was that I expected it to show up while waiting at the list of books, but it only showed up if I went into an other book and than back to the list (or I think close and open the app). It would be nice if the new book gets put in while staying at the book list. 

An other small issue is that a book showed up while copying the files from my pc, but since not all the files where copied over it did not have all the chapters in the list, and started with a chapter in the middle. reloading the book by returning to the home screen and than back after the transfer was complete put in the missing chapters, but the progress was now halfway the book. It would be nice if you could wait loading the book till the transfer completes, but I can see that that could be difficult to implement. 

Both are not major issues and my main problem is resolved with this update.

**Comment by marksz** [comment]
I'm consistently having this problem (long several minute delays) on a Moto One 5g Ace running Android 11 with Voice 6.4.1.  I believe Voice used to show most recently added books first, but now the order seems random.  If the entire list must be rescanned, could it be set to add the most recent books first?  It's frustrating when I've just finished a book that ends with a cliff hanger, and have to play the next in another app for a while before I can play it faster in Voice.  

In the past, I've had problems with the book list getting corrupted, or voice getting stuck and refusing to play at a certain point when another player handled the same file just fine.  This hasn't been a problem in the most recent versions.  This is way better than all the other free players I've used.

Ideas that might help:
1) Sort the audiobook folder with most recent modify timestamps first when loading the book list.
    Start showing books before the entire collection has been scanned.
2) Add sort order preferences to the settings and/or search menus.
3) Allow file managers to see Voice as an open with option for audio file types.
    File Manager 6.13.0 Pro sees about 7 other apps for opening an audiobook, most of them music players, but not Voice.
4) Add a menu to show the most recently added book on the device independent of a stale list
