### ISSUE TITLE
Ogg skipping does not work 

### ISSUE THREAD

**Issue by ovidiub13** [PaulWoitaschek/MaterialAudiobookPlayer#564]
Skipping or jumping to specific time when playing an ogg file jumps to random places. 

Skipping back jumps once and then refuses to jump back further than a specific position. 

I used this ogg file: https://archive.org/download/TheMartianAndyWeirAudioBook/The%20Martian%20-%20Andy%20Weir.ogg

**Comment by nioncode** [comment]
Works fine in 3.3.1 on my Nexus 5x on Android 7.1.1.

Please reopen with more details about your device if it does not work on your device.

**Comment by nioncode** [comment]
@PaulWoitaschek should be closed

**Comment by PaulWoitaschek** [comment]
Thanks for helping out with this!
