### ISSUE TITLE
About menu missing in latest beta

### ISSUE THREAD

**Issue by ovidiub13** [PaulWoitaschek/MaterialAudiobookPlayer#565]
In the latest update from Google play, (I'm in the beta testing program) there is  no menu that gives info about the application. 

Also there are many menus missing, that were available in older versions of the app.

**Comment by PaulWoitaschek** [comment]
What kind of menus? There was never a menu that gives info about the application.

**Comment by ovidiub13** [comment]
There were some menus IIRC that give info about the app and where to report bugs. I might me mistaking this with the Google Play description.

If I am, please close this.

**Comment by PaulWoitaschek** [comment]
Seems like the play description. You can click on the hearth in the top right in the settings menu to go to github / transifex
