### ISSUE TITLE
in beta version: crash after 10 - 15 seconds​

### ISSUE THREAD

**Issue by FolkyHobbit** [PaulWoitaschek/MaterialAudiobookPlayer#567]
After the latest update in the beta programming the app started crashing after 10 to 15 seconds. I did submit a crash report via the android crash dialogue. Let me know if and how i can provide you more information.

**Comment by PaulWoitaschek** [comment]
I woke up 10 minutes ago and pushed an update. Please comment if it does not fix.

**Comment by FolkyHobbit** [comment]
The update fixed the problem. Thank you for this fast response.
