### ISSUE TITLE
App is devouring battery like there's no tomorrow.

### ISSUE THREAD

**Issue by bagarwa** [PaulWoitaschek/MaterialAudiobookPlayer#569]
I am using the latest version available on the play store. I'm using it on my Nexus 6P, running Android 7.1.2 beta. I have selected just one folder from my internal memory for only one audiobook. And when I play the book, the app starts devouring the battery. The phone becomes so warm that I can feel the heat through the thick case it has on. And 2 hour of playback brought the battery from 85% to 15%...!!! And even after quitting the app, looks like it is keeping something running in the background, because the battery keeps draining even when the phone is plugged in (to the computer via usb port though)..!! Only a reboot fixes this drain.

Needless to say, the app is pretty useless this way. Please let me know if I can generate any logs to help with this.

**Comment by PaulWoitaschek** [comment]
Can you post a screenshot with the battery stats?

**Comment by bagarwa** [comment]
Sorry, I flashed Android O developer preview 1 yesterday and the battery drain isn't happening since then. So, it might've been an Android 7.1.2 issue.
