### ISSUE TITLE
Cannot seek in mka/opus files

### ISSUE THREAD

**Issue by wessven** [PaulWoitaschek/MaterialAudiobookPlayer#572]
I have a set of files which are encoded with OPUS and contained in MKA files.  Material Player plays these files just fine.  However, I am unable to seek forward or backward within these files.  I can move the slider forwards or backwards, but it always jumps back to where it was.

Additionally, when the player exits and it restarts, it does not remember the position of the file where it was.  It does remember the position in the playlist, but not where in the file playback had stopped.

**Comment by gabriellluz** [comment]
+1 I have files in MKA e OPUS files, too! I second that.

**Comment by gabriellluz** [comment]
I think MKA with OPUS inside should be the next standard for audiobooks since it can have a lot of information like tags, covers, extensive metadata.

**Comment by PaulWoitaschek** [comment]
Will be fixed in the next version. Please report if not so.
