### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by alexagr** [PaulWoitaschek/MaterialAudiobookPlayer#577]
After latest update the app crashes on start (starts showing tiles and then closes after about a second). I tried clearing app data, but this doesn't help - as soon as I specify my audiobooks folder, the same problem happens.
My phone is Meizu M1 Note. And the previous versions of the app were working perfectly fine.

**Comment by alexagr** [comment]
Seems that the issue is related to folder with AAC files. As soon as I removed it the crashes were gone.

**Comment by PaulWoitaschek** [comment]
It's crashing because your phone has not enough memory for parsing the chapters.

**Comment by PaulWoitaschek** [comment]
It looks like you have one really huge file (1,2 GB?)

**Comment by PaulWoitaschek** [comment]
Can you try if this version fixes it for you?

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/download/3.2.0.2/180-MaterialAudiobookPlayer-opensource-release-3.2.0.2.apk

**Comment by alexagr** [comment]
Sorry I already deleted those AAC files.
So can't reproduce the crash any more.

**Comment by PaulWoitaschek** [comment]
Damn. So let's just hope it works or someone else can reproduce this.

**Comment by spackmat** [comment]
I have the same problem and your 3.2.0.2 doesn't fix it. In my case, it's also a folder with .aac files (m4a works fine) which I think don't have chapter marks. I can reproduce it with a folder with just a single .aac file in it. I can send you a copy, if you want.

**Comment by spackmat** [comment]
The new 3.2.0.3 fixes the crashes, but now, I cannot play those .aac files. Very strange: Track 1 jumps directly to Track 2, which is played correctly. Track 3 jumps to track 4.

The file I sent you cannot be played at all. This worked in older versions.

**Comment by PaulWoitaschek** [comment]
Can you send me a file with which it does not work? The one your sent me has not issues isolated.

**Comment by spackmat** [comment]
The file I sent you cannot be played on my device. When I copy it in a new folder, it is found by the app, but when I hit the play button, it stops immediately. When there are other files in the folder, hitting play skips the file and the next one is played.

**Comment by PaulWoitaschek** [comment]
If this is not resolved, please comment!

**Comment by spackmat** [comment]
For me it is solved now. Thanks.

**Comment by slindner211** [comment]
I still got the same issue in version 3.3.3.2. The player crashes on my OnePlus 3T when there is a mp4 file in the specified folder which contains chapters. Works with ordinary mp4 though.

**Comment by PaulWoitaschek** [comment]
Can you send me such a file to the mail in my github profile?

**Comment by slindner211** [comment]
the smallest file i have this issue with is still 270mb. I could send it to you on another way though.

**Comment by PaulWoitaschek** [comment]
That would be great. Google Drive + Link will work too :)

**Comment by cyreb7** [comment]
Same issue here. Tried with V3.3.3 and it still crashed. I will send @PaulWoitaschek a link to the file.

**Comment by PaulWoitaschek** [comment]
Thanks you two. Was the exact same issue for both files. Will be fixed in the next version.
