### ISSUE TITLE
Using play back speed feature causes "skips"/corrupted sound

### ISSUE THREAD

**Issue by shrub77** [PaulWoitaschek/MaterialAudiobookPlayer#578]
As mentioned in the title, using the playback speed feature to something other than 1.0x causes the audio to sound corrupted, similar to a disk skipping. I can upload the sound if needed. Let me know if anything​ else is needed

Moto x pure edition Android 6.0

**Comment by PaulWoitaschek** [comment]
Yes, please upload a sample file. Which App version are you using?

**Comment by shrub77** [comment]
The issue seemed to stop with the recent update, I will reopen this if it occurs again with an audio sample
