### ISSUE TITLE
Please add support for .ogg files.

### ISSUE THREAD

**Issue by danorul9** [PaulWoitaschek/MaterialAudiobookPlayer#579]
Unable to scurb through ogg / vorbis files.
Doesn't​ save the last played position as well.

**Comment by PaulWoitaschek** [comment]
Which version are you using?

**Comment by danorul9** [comment]
Hi Paul,

Thankyou for the speedy response. I am using 3.2.0.3 on Android 7.0.

Thanks and Regards,
Dano Jose

*Phone:*+61 424 132 785  <%2B61%20424%20132%20785>
*Email:* danorul9@gmail.com
*Facebook:* www.facebook.com/DanoJose.Official
*Youtube:* *https://www.youtube.com/danojose
<https://www.youtube.com/danojose>*

**Comment by PaulWoitaschek** [comment]
Please update to 3.3 and report if the problem still persists.
