### ISSUE TITLE
Seeking fails in some mp3 files

### ISSUE THREAD

**Issue by nioncode** [PaulWoitaschek/MaterialAudiobookPlayer#583]
Since 3848eb57bd6fa3d5b95a7124db3249269692680c, seeking fails in one of my audiobooks. 

Whenever I attempt to seek somewhere, the playback position resets to '0:00' and the chapter starts from the beginning.

It fails on every of its mp3 files, but it works fine for other audiobooks I currently have on the phone, so I assume that it might have something to do with the format / encoding of the file that ExoPlayer doesn't handle properly. Can we revert back to your AndroidPlayer until this is resolved in ExoPlayer?

**Comment by nioncode** [comment]
A pause / resume cycle also resets the chapter back to the beginning.

However, playing the file with the https://github.com/google/ExoPlayer demo works fine (i.e. pausing + resuming works).

**Comment by PaulWoitaschek** [comment]
Can you send me such a file?

**Comment by PaulWoitaschek** [comment]
Did you try the latest version? It has flags for mp3 constant seeking set.

**Comment by nioncode** [comment]
Great, everything works again :)
Sorry for the noise.
