### ISSUE TITLE
Random crashes on Metadata scan

### ISSUE THREAD

**Issue by nioncode** [PaulWoitaschek/MaterialAudiobookPlayer#584]
In `MetaDataAnalyzer.prepare()`, the call to `MediaMetadataRetriever.setDataSource` sometimes (randomly?) throws a RuntimeException that is not catched and thus crashes the app when adding a new book.

Also, is it correct to simply ignore thrown Exception's? This will lead to wrong / empty metadata.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. As of 5232dec79cec6802de724018298c8bbf99bfb51a that is catched and a second attempt to prepare the file is being made.
As of 4d068080f2c483cf173ce8e9780b1e9d3273e1ca  if the second attempt fails, the chapter is parsed anyways but without additional metadata so the user can still use that file.

Feel free to do more code reviews, that's great!
