### ISSUE TITLE
DurationAnalyzer broken: adding book does nothing

### ISSUE THREAD

**Issue by nioncode** [PaulWoitaschek/MaterialAudiobookPlayer#585]
Somehow, `doOnNext` for the `waitForIdle` sometimes does not get called, which lets `DurationAnalyzer` wait infinitely for the result.

I'm new to RxJava, but my guess is that this is some kind of race condition that results in no observers, when `playbackStateSubject.onNext(playbackState)` gets invoked.

Adding `d { "hasObservers: ${playbackStateSubject.hasObservers()}` in the `onPlayerStateChanged` callback shows, that the subject has no observers when this bug is triggered.

**Comment by PaulWoitaschek** [comment]
Thanks!

Should be fixed as of 2d48813deda6d2d7c6a2f643af35574a1579abab
