### ISSUE TITLE
Fix build on circle CI due to exoplayer

### ISSUE THREAD

**Issue by Eifelschaf** [PaulWoitaschek/MaterialAudiobookPlayer#590]
The full error message is:

    Execution failed for task ':exoplayer-opus:prepareOpus'.
    > java.io.IOException: Command convert_android_asm.sh exited with exitCode=127

According to [stackoverflow](https://stackoverflow.com/questions/1763156/127-return-code-from) there might be a setup issue on circle CI:

> Value 127 is returned by /bin/sh when the given command is not found within your PATH system variable 
> and it is not a built-in shell command. In other words, the system doesn't understand your command, because it doesn't know where to find the binary you're trying to call.

**Comment by PaulWoitaschek** [comment]
The question is why. And why does it work using Android studio? That's a script in the jni dir:
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/exoplayer-opus/src/main/jni/convert_android_asm.sh

**Comment by Eifelschaf** [comment]
i'll have a look at the script. Perhaps there's some binary called that's standard in our setups, but not on circleci.

**Comment by PaulWoitaschek** [comment]
When you clone the repo and assemble from command line you should see the same issue.

**Comment by Eifelschaf** [comment]
I'll give it a try

Paul Woitaschek <notifications@github.com> schrieb am Mo., 22. Mai 2017,
21:17:

**Comment by Eifelschaf** [comment]
Git it! Just add a ./ in front of the `convert_android_asm.sh` to mark it as a local executable instead of something on the PATH. However now I get a new issue:

    selected processor does not support ARM mode

**Comment by Eifelschaf** [comment]
There, I fixed it: https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/pull/592

**Comment by PaulWoitaschek** [comment]
Thanks! Next failure is:

```
Your build has exceeded the memory limit of 4G on 1 container. The results of this build are likely invalid. We have taken a snapshot of the memory usage at the time, which you can find in a build artifact named `memory-usage.txt`. The RSS column in this file shows the amount of memory used by each process, measured in kilobytes. 
```

The memory-usage is here: https://gist.github.com/PaulWoitaschek/49cada56b67e1f01a9e79544fc31385c

No idea how to fix that.

**Comment by PaulWoitaschek** [comment]
Thanks! Next failure is [here](https://circleci.com/gh/PaulWoitaschek/MaterialAudiobookPlayer/123).

>Your build has exceeded the memory limit of 4G on 1 container. The results of this build are likely invalid. We have taken a snapshot of the memory usage at the time, which you can find in a build artifact named `memory-usage.txt`. The RSS column in this file shows the amount of memory used by each process, measured in kilobytes. 

The [memory-usage.txt](https://gist.github.com/PaulWoitaschek/49cada56b67e1f01a9e79544fc31385c
)

No idea how to fix that. I added an environment variable and a gradle script to disable pre-dexing which works as the line `PREDEX DISABLED` correctly logs.

**Comment by PaulWoitaschek** [comment]
Fixed :)
