### ISSUE TITLE
Adjust the length to the speed of playing. 

### ISSUE THREAD

**Issue by FaisalFehad** [PaulWoitaschek/MaterialAudiobookPlayer#591]
Currently, the total length of a book assumes that you would  play it with 1X, which is not always the case. The total length should be adjusted to the playing speed, otherwise it becomes irrelevant.

**Comment by PaulWoitaschek** [comment]
I think that would be super confusing.

**Comment by jozic** [comment]
i can also see having this as a useful addition
maybe having a flag in settings (account for speed in total length) disabled by default may be an option?
