### ISSUE TITLE
Incorrect plural form in Russian translation

### ISSUE THREAD

**Issue by antonv6** [PaulWoitaschek/MaterialAudiobookPlayer#593]
Basically, all strings with `<item quantity="few">` assume the same form as `<item quantity="one">`, which is not how Russian language works (some examples: [search](https://github.com/search?utf8=%E2%9C%93&q=%3Citem+quantity%3D%22few%22%3E+extension%3Axml+path%3Avalues-ru&type=Code&ref=advsearch&l=&l=)). I'd fix them in a PR, but you seem to reject those (#532). And unfortunately, to even look at this translation in Transifex I need a permission to join the team. Sigh.

So can you accept my request there? My profile is https://www.transifex.com/user/profile/av6/

**Comment by PaulWoitaschek** [comment]
How does the russian language work? Is there a specific russion for people from russia? Else please join the regular russian language so we don't have duplication.

**Comment by antonv6** [comment]
[How it works with plurals](http://developer.alexanderklimov.ru/android/theory/plurals.php). And as to why Russian (Russia) language exists, it's just another locale (`ru_RU`): think of it like `en`, `en_US` and `en_GB`, for example. Most projects only really need `ru` locale though.

I've sent another request.

**Comment by PaulWoitaschek** [comment]
Thanks for translating :)
