### ISSUE TITLE
crash on startup in beta 

### ISSUE THREAD

**Issue by FolkyHobbit** [PaulWoitaschek/MaterialAudiobookPlayer#596]
The app started crashing directly after start up since the last update last night in the beta program. I submitted a crash report via the android dialogue. If I in any way can provide more information, let me know.

**Comment by PaulWoitaschek** [comment]
Which version are you using?

**Comment by FolkyHobbit** [comment]
according to the play store version 3.3.3.6.2

**Comment by FolkyHobbit** [comment]
I see there is a update available I will check if that fixes it.

**Comment by FolkyHobbit** [comment]
Yes new update to 3.3.5 fixed it again, thank you!
