### ISSUE TITLE
Continue playing audio files after one finish

### ISSUE THREAD

**Issue by maestrozen** [PaulWoitaschek/MaterialAudiobookPlayer#597]
I have a audiobook with lots of audio files 7 minutes long for each chapter. I want to play them automatically like one. But after one end I have to manually go to the other file... Even though they are loaded and in order In the player. Maybe it's just my case.

**Comment by PaulWoitaschek** [comment]
You should add them add a single book folder. You have added then as your main audiobook folder so it thinks each file is a separate book.
