### ISSUE TITLE
3.3.4 crashes 

### ISSUE THREAD

**Issue by roth-a** [PaulWoitaschek/MaterialAudiobookPlayer#598]
3.3.4 crashes directly after the start. I'm unable to do anything. I already cleared the data and cache but without success. 
The previous version works without problems. 

I have an lg g3. Android 5.0.

**Comment by PaulWoitaschek** [comment]
Please update your app.

**Comment by roth-a** [comment]
3.3.4 it's the newest available in f-droid

**Comment by PaulWoitaschek** [comment]
Fdroid takes some time to build stuff. You can get the latest release from the releases tab too.
