### ISSUE TITLE
Bug: Volume stays low when other app plays audio

### ISSUE THREAD

**Issue by taiko000** [PaulWoitaschek/MaterialAudiobookPlayer#599]
When another app plays audio for a short time, the player's volume is decreased. The expected behavior is that the player's volume increases again, after the other app finished playing it's audio. But the volume stays low and is independent of the system volume and cannot increased again by the system volume controls. Only force killing helps to restore the player to its original state.

**Comment by PaulWoitaschek** [comment]
So you have a Samsung device?

**Comment by taiko000** [comment]
LG Nexus 4, Android 5.1.1 stock

**Comment by PaulWoitaschek** [comment]
Which version of the app are you using? Does this happen each single time?

**Comment by taiko000** [comment]
My mistake, the current update from google play just fixed the issue.
