### ISSUE TITLE
Can't select folder on sdcard as audiobook source

### ISSUE THREAD

**Issue by zachfrey** [PaulWoitaschek/MaterialAudiobookPlayer#600]
Please include the following details in your bug report:

App-Version: 3.3.5
Phone Name: V10
Android Version: 6.0

When prompted to choose an Audiobook folder, I can not select folders on my sdcard. They are not visible in the offered list of folders.

**Comment by PaulWoitaschek** [comment]
What's the path of the sd card?

**Comment by zachfrey** [comment]
/root/storage/6362-6533

Never mind, my confusion. I thought I had it mounted at /sdcard. If I select "All", it shows me that folder option and then I can select the "Audiobooks" folder I had created.

**Comment by sandybeachit** [comment]
Hi zachrey just to confirm your not having any issues, this is not a bug?

**Comment by zachfrey** [comment]
Yes, not a bug. This issue can be closed.
