### ISSUE TITLE
Material Player jumps to position 27:03:12 immediately

### ISSUE THREAD

**Issue by Mike-de** [PaulWoitaschek/MaterialAudiobookPlayer#601]
I like the application very much. Since round about 3 software versions I have the issue that the the player do not play audio files (mp3) anymore. Material player stops after 2-3 seconds. If I press "pause" and "play" again, it jumps to position 27:03:12. The audio files are much shorter. e.g. 2:38.39. If I start a audio book again, it jumps directly to 27:03:12 without playing. 
Uninstall and install the application doesn't help

App-Version: 3.3.5.
Phone Name: Amazon firephone 
Android Version: 4.6.6.1
thank you Michael

**Comment by PaulWoitaschek** [comment]
Can you sent me such a file to the mail in my github profile?

**Comment by Mike-de** [comment]
it happens with any mp3 file. I just tested it with a file from here: https://www.freesound.org/people/ERH/sounds/29589/
It is just a 22sec sample. The player jumps immediately to 42:37
I hope it is fine to attach this to here. The example is license free and there should be no legal issues. 
[licencefreemp3.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/1066430/licencefreemp3.zip)

**Comment by PaulWoitaschek** [comment]
It seems there are specific issues with FireOS (which seems to be not a real android).
Amazon ported ExoPlayer so one could fork MAP and include that port:

https://github.com/amzn/exoplayer-amazon-port

**Comment by Mike-de** [comment]
probably yes, it is strange that it worked with a former versions of the material player. is there an old version e.g. 3.2 somewhere available?

**Comment by PaulWoitaschek** [comment]
Yes, check the releases tab. If any version is missing I can build it for you, just tell me!
