### ISSUE TITLE
Incorrect chapters for some .m4b files

### ISSUE THREAD

**Issue by wberrier** [PaulWoitaschek/MaterialAudiobookPlayer#611]
Please include the following details in your bug report:

App-Version: 3.3.6.2
Phone Name: RW 1st Gen Moto X
Android Version: 5.1

I have a couple of files with issues...

In this one, the chapters don't show up at all:

http://media2.ldscdn.org/assets/scripture-and-lesson-support/teachings-of-presidents-of-the-church-gordon-b-hinckley/2017-01-00-teachings-of-presidents-of-the-church-gordon-b-hinckley-128k-eng.m4b?download=true

I have another file that I encoded myself, but for some reason, only the first 4 chapters show up. On all the other files I've encoded myself they are correct. Not sure what's up with that yet. Here's a link to the file:

https://drive.google.com/open?id=0B5DxbhZHghuGNlg3TEZ2T1ZGVnM

**Comment by PaulWoitaschek** [comment]
Can you check if https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v3.3.6.4 fixes it for you?

**Comment by wberrier** [comment]
Yes, that worked great, thanks!
