### ISSUE TITLE
Package de.ph1b.audiobook signatures do not match the previously installed version

### ISSUE THREAD

**Issue by br3wski3** [PaulWoitaschek/MaterialAudiobookPlayer#615]
Tried to update to version from Git release tab over version installed from Play but got "Package de.ph1b.audiobook signatures do not match the previously installed version" - is this expected? Even for the latest Play release version number with regard to the version on the Git release tab?

**Comment by PaulWoitaschek** [comment]
That's expected. It's because of the new play signing feature.
