### ISSUE TITLE
New language translation import

### ISSUE THREAD

**Issue by naglis** [PaulWoitaschek/MaterialAudiobookPlayer#617]
Hi,

I saw that you have [recently imported](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/commit/53ecc8291a7cb513351d974e2e8a1ca6827f032b) translation strings from Transifex, however it seems that the newly added languages are not picked up (`lt_LT` in particular).

Could you please take a quick look into it?

**Comment by PaulWoitaschek** [comment]
Wtf. There are all these translators making the effort and translating the app. And then after multiple months someone mentions that they never see their translations in the app. 

It was acutally kind of a bug in the translation pull script which was not pulling new languages.
If you know you translated something and there is a new release which does not contain it, let me know!

New:
-ar -tr -sl -lz -hi -fa -da

**Comment by naglis** [comment]
Thanks!
