### ISSUE TITLE
Add support for webm/matroska chapters for opus audiobooks

### ISSUE THREAD

**Issue by wberrier** [PaulWoitaschek/MaterialAudiobookPlayer#619]
Opus is an ideal codec for speech and audiobooks:

* high quality for low-bitrate speech
* webm/matroska chapter support
* open standard (ie: webm)

There are some .mka (matroska audio) sample files here with chapters:

https://drive.google.com/drive/folders/0B5DxbhZHghuGMnRkY1VpakI2TjA?usp=sharing

Note, webm supports a subset of matroska chapter features:

https://www.webmproject.org/docs/container/#chapters

**Comment by PaulWoitaschek** [comment]
And these files don't play?

**Comment by wberrier** [comment]
All the files play perfectly.

They are linked as sample mka/opus files that include chapters (and also cover art, author and title info).

**Comment by p2004a** [comment]
Opus is really great. "Native" container for opus is ogg (files with .opus extension are ogg files) which also supports chapters using this simple extension: https://wiki.xiph.org/Chapter_Extension

I'm currently working on a pull request that adds support for extracting chapters from ogg/opus and ogg/vorbis files. It works on a simple ogg/opus file. I have to add more tests and clean up the code.

**Comment by wberrier** [comment]
Last time I checked (many years ago) ogg comment chapter support was a heated topic, skewing me towards matroska.

It's great to see that ogg has an adopted chapter extension, and it looks like several players support it (ffmpeg, vlc, more?).

I do think matroska is a better container, but I'd gladly welcome ogg chapter support, thanks!

At some point I'll update the posted ogg/opus example files to contain chapters.  (I'll probably add coverart as well, although that's probably another topic).

Looking forward to the feature...

**Comment by PaulWoitaschek** [comment]
> I'm currently working on a pull request that adds support for extracting chapters from ogg/opus and ogg/vorbis files. It works on a simple ogg/opus file. I have to add more tests and clean up the code.

That's good news! Looking forward for your PR. If possible add test cases using non copy-right protected files.

I started with the matroska ebml parsing, but it will really take some time and I don't have too much spare time currently.

**Comment by p2004a** [comment]
> I started with the matroska ebml parsing, but it will really take some time and I don't have too much spare time currently.

How deep are you in it? If not much, I think, I can find some time to try to extract chapters using this library: https://github.com/kokorin/jebml

**Comment by PaulWoitaschek** [comment]
Sure, feel free to do so. Why did you pick that library over others?

**Comment by p2004a** [comment]
I picked the JEBML because it's referenced from https://www.matroska.org/team/source-code.html. To be precise, the repo I referenced is a [maven exported](http://www.mvnrepository.com/artifact/com.github.kokorin/jebml/2.3) fork of a person who recently contributed to it the most.

**Comment by PaulWoitaschek** [comment]
Looks good to me. Thanks for your contribution!

**Comment by p2004a** [comment]
@wberrier The mka files you've linked are invalid. Both ffprobe and mkvinfo fail when reading them, so is JEBML used in my pull request. I've recreated this file from mp3s from https://librivox.org/the-count-of-monte-cristo-version-3-by-alexandre-dumas/ its here: https://drive.google.com/file/d/0B8b4jUX2s15VTWRKbjk4bmRIX1E/view?usp=sharing Extracting chapters from this file works fine, but extracting other metadata and seeking fails, I will open a new issue.

**Comment by wberrier** [comment]
@p2004a I verified that mkvinfo fails against the mka files I authored.  I'll fix them when I get a chance.

As a side note, I'm also in the middle of adding an ogg/vorbis file with chapter comments.

**Comment by PaulWoitaschek** [comment]
How did you add the tags? @wberrier

**Comment by wberrier** [comment]
I created the files in the audiobook_samples drive with a tool I wrote:

https://bitbucket.org/wberrier/audiobook_tool

but under the hood it just uses mkvpropedit, mkvextract, mkvinfo for mka files.

I've remastered the opus and vorbis .mka files.  Please try them out.  mkvinfo doesn't complain about them any longer.

I've also added an .ogg file with chapter comments.  Sidenote: I was hoping to be able to use vorbiscomment with .opus files, but vorbiscomment only works with ogg/vorbis files.  I'll have to find another solution there (probably mutagen) to tag .opus files, further convincing me that matroska is a better fit.  In any case, I'm still going to add .opus support to the above tool.

**Comment by p2004a** [comment]
@wberrier The only way to add chapters to .opus files I'm aware of is to specify them through `--comment`s options to opusenc. (For my own usage I implemented a `--metdata-file` flag in opusenc: https://github.com/p2004a/opus-tools/tree/metadata-file)

**Comment by wberrier** [comment]
I've updated the .opus file in the above linked audiobook_samples to have embedded chapters.

I ended up adding the opus chapters via the `mutagen` python library inside `audiobook_tool`.

Thanks again for all the work on this!
