### ISSUE TITLE
Resume timestamp wrong when playing long mp3s

### ISSUE THREAD

**Issue by Groundrunner** [PaulWoitaschek/MaterialAudiobookPlayer#624]
I experience an issue when listening to very long audiobooks, which are not separated into chapters. When pausing and then resuming, the player doesn't resume at the correct position.

Further details:
The book I am currently listening to is an mp3 about 40 hours long (a single "chapter" of 40 hours). The following steps reproduce the bug:
1. I playback the audiobook and watch the timeline progress. 
2. After listening a while (say 20 minutes) I pause playback. Let's say the timeline now displays 5 hours 50 minutes.
3. When resuming, the timeline resumes at the "correct" position of 5 hours 50 minutes, but I have to rewind to about 5 hours 47 minutes to resume at the actual audio position I paused at.

It seems the longer I listen before pausing, the longer I will have to rewind when resuming.

App-Version: 3.3.6.3
Phone Name: Samsung Galaxy S7
Android Version: 7.0

P.S. Thank you for your great work. This is absolutely my favorite audiobook app.

**Comment by PaulWoitaschek** [comment]
Thanks for the report. I can't really do anything here. It's most likely that the mp3 do not have a proper seek table so ExoPlayer cant determine the very exact position.
