### ISSUE TITLE
Widget stopped working with 3.4.0

### ISSUE THREAD

**Issue by yaymeh** [PaulWoitaschek/MaterialAudiobookPlayer#627]
With version 3.4.0, the widget stopped working. Tried removing / re-adding it (+ rebooting): the thumbnail isn't visible any more and the three buttons - while visible - do nothing at all.

Everything else (including the notification and its thumbnail + buttons) still work fine as far as I can tell. 

I only get log messages when I add / remove the widget, tapping it or the buttons is silent. Everything looks very different depending on which home app I use and there's a lot of spam - not sure if I managed to find something relevant:

Trebuchet:
```javascript7-19 18:10:32.396  4277  4277 D WidgetsContainerView: onLonglick dragging enabled?.
07-19 18:10:32.604  3920  4393 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
07-19 18:10:32.604  3920  4393 E AndroidRuntime: Process: de.ph1b.audiobook, PID: 3920
07-19 18:10:32.604  3920  4393 E AndroidRuntime: java.lang.IllegalArgumentException: At least one dimension has to be positive number.
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at com.squareup.picasso.Request$Builder.resize(Request.java:305)
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at com.squareup.picasso.RequestCreator.resize(RequestCreator.java:219)
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at de.ph1b.audiobook.features.widget.WidgetUpdateService.initElements(WidgetUpdateService.kt:196)
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at de.ph1b.audiobook.features.widget.WidgetUpdateService.access$initElements(WidgetUpdateService.kt:41)
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at de.ph1b.audiobook.features.widget.WidgetUpdateService$updateWidget$1.run(WidgetUpdateService.kt:108)
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-19 18:10:32.604  3920  4393 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
07-19 18:10:32.612  3920  4398 I Process : Sending signal. PID: 3920 SIG: 9
07-19 18:10:32.643   344  1194 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
07-19 18:10:32.644   719  1723 I ActivityManager: Process de.ph1b.audiobook (pid 3920) has died
07-19 18:10:32.644   719  1723 D ActivityManager: cleanUpApplicationRecord -- 3920
```

ADW (this too might or might not be related):
<code>MediaMetadataRetrieverJNI: getEmbeddedPicture: Call to getEmbeddedPicture failed.</code>

**Comment by yaymeh** [comment]
Those lines (in UpdateWidget) work fine with the "Pixel" launcher, but they don't seem to work with all launchers / they always give you 0 for everything with some launchers:
```    
          val minHeightDp = opts.getInt(AppWidgetManager.OPTION_APPWIDGET_MIN_HEIGHT)
          val maxHeightDp = opts.getInt(AppWidgetManager.OPTION_APPWIDGET_MAX_HEIGHT)
          val minWidthDp = opts.getInt(AppWidgetManager.OPTION_APPWIDGET_MIN_WIDTH)
          val maxWidthDp = opts.getInt(AppWidgetManager.OPTION_APPWIDGET_MAX_WIDTH)
```
... and I have not been able to figure out why exactly. Maybe older launchers don't have it implemented.

What causes the widget to fail appears to be the cover resize to 0. I tested checking if coverSize is 0 before resizing - It's more of a workaround than a solution I guess, but with just this change in initElements, the widget seems to work in all launchers again:
```
        if (coverSize > 0) {
          cover = Picasso.with(this@WidgetUpdateService)
              .load(coverFile)
              .resize(coverSize, coverSize)
              .get()
        } else {
          cover = Picasso.with(this@WidgetUpdateService)
            .load(coverFile)
            .get()
        }
```

**Comment by PaulWoitaschek** [comment]
Thanks, I fixed that. I think it's actually a bug if a launcher does not implement this.

It's supported by our min-sdk 16, launchers should call
https://developer.android.com/reference/android/appwidget/AppWidgetHostView.html#updateAppWidgetSize
