### ISSUE TITLE
License fraud?

### ISSUE THREAD

**Issue by gsantner** [PaulWoitaschek/MaterialAudiobookPlayer#630]
This may be worth a look. Just pasting.

* https://codecanyon.net/item/material-music-player/19422996?s_rank=467
* https://codecanyon.net/item/material-music-player/screenshots/19422996

@PaulWoitaschek

**Comment by PaulWoitaschek** [comment]
I contacted the website owners and they don't care if they sell fraud or not. And I don't have the time for investigating too much into this kind of ***.

But thanks for reporting :)

**Comment by gsantner** [comment]
eMBee "someone else" is me :P
