### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by mziehm** [PaulWoitaschek/MaterialAudiobookPlayer#631]
Please update the changelog (last changelog entry is 3.0.9 but current version 3.4.0, with at least the following versions in between: 
3.2.0
3.2.0.1
3.2.0.2
3.2.0.3
3.3.3.3
3.3.3.4
3.3.3.5
3.3.3.6
3.3.3.6.2
3.3.4
3.3.5
3.3.6.2
3.3.6.3
3.3.6.4
3.4.0

Thanks - really enjoy the app, but don't like updating not knowing what for.

**Comment by PaulWoitaschek** [comment]
Done 911868a368b5cad4de89dc97d9987f470727417c
