### ISSUE TITLE
Add a quick bookmark feature.

### ISSUE THREAD

**Issue by basstwo** [PaulWoitaschek/MaterialAudiobookPlayer#639]
My suggestion is to add a preference that changes the functionality of the 'bookmark' button.  It would let you click the button and it would save a bookmark without asking for a name or even leaving the main play screen.  OverDrive does this, for reference.

I like to be able to lock in where I started in case I fall asleep while listening.

App-Version: 3.4.0
Phone Name:. Google Pixel
Android Version: 7.1.2

**Comment by PaulWoitaschek** [comment]
When you open the sleep timer, there is a switch for automatically adding a bookmark.
