### ISSUE TITLE
Option to remember Volume Boots

### ISSUE THREAD

**Issue by NeuroNex** [PaulWoitaschek/MaterialAudiobookPlayer#640]
App-Version: 3.4.0
Phone Name: Oneplus One
Android Version: 6.01

Currently the Volume Boost is reset to 0 when the app restarts. Would be more convenient to have a preference setting "Remember Volume Boost" to have this set permanently.

Thanks very much in advance.

**Comment by PaulWoitaschek** [comment]
I can't confirm this. Can someone?

**Comment by mtvjr** [comment]
It does not reset when I try.

**Comment by NeuroNex** [comment]
Oh this is true, even after a reboot. I see the boost volume staying the same. Is it a "per book" setting? Because the boost level are preserved on the 2 books I have read. Switching to new books bring boost to zero.

May be it makes sense to have this "per book" as the sound level may varies per book. Nevertheless, I notice for convenience, I think it would make sense to have this boost set for "all books". In case there is a book which already has sound level louder than average, it is simpler to use the phone volume button to volume down. Or in my case the bluetooth device volume down (in the car) or the external Bluetooth spearker.

If this is "per book" setting. Would it be OK to change my request to "Remember Boost Level for all books" ?

**Comment by PaulWoitaschek** [comment]
Good to see that it works. The volume boost setting is persisted in the database.

I don't think it makes sense to generally add a volume boost to all books as there might be really different audio formats.
